export const metadata = {
  title: "Terms of Service · Vocateur",
};

export default function TermsPage() {
  return (
    <main className="mx-auto flex w-full max-w-2xl flex-1 flex-col gap-8 px-6 py-20">
      <div className="flex flex-col gap-2">
        <h1 className="font-[family-name:var(--font-display)] text-4xl font-medium tracking-tight">
          Terms of Service
        </h1>
        <p className="text-sm text-foreground/40">Effective July 21, 2026</p>
      </div>

      <div className="flex flex-col gap-8 text-sm leading-relaxed text-foreground/70">
        <section className="flex flex-col gap-2">
          <h2 className="text-base font-semibold text-foreground">Agreement to these terms</h2>
          <p>
            Vocateur (&ldquo;we,&rdquo; &ldquo;us&rdquo;) operates vocateur.app. By creating an account or using
            Vocateur, you agree to these terms. If you don&rsquo;t agree, don&rsquo;t use the service. See our{" "}
            <a href="/privacy" className="underline underline-offset-2 hover:text-foreground">
              Privacy Policy
            </a>{" "}
            for how we handle your data.
          </p>
        </section>

        <section className="flex flex-col gap-2">
          <h2 className="text-base font-semibold text-foreground">What Vocateur is</h2>
          <p>
            Vocateur is a career-matching assessment. It generates career matches, a personalized roadmap, and
            access to an AI career-advisor chat based on your responses. Vocateur is intended for users age 13 and
            older. See our Privacy Policy for details.
          </p>
        </section>

        <section className="flex flex-col gap-2">
          <h2 className="text-base font-semibold text-foreground">AI-generated content: please read this</h2>
          <p>
            Your results, roadmap, market outlook figures, and advisor/mock-interview responses are generated by
            AI, informed by real third-party data (like U.S. Bureau of Labor Statistics projections) where noted,
            but they are guidance, not guarantees. Career outcomes, job-market conditions, and salary figures
            change, and no assessment can predict your individual outcome with certainty. Vocateur is not a
            substitute for professional career counseling, financial, legal, or immigration advice, and we&rsquo;re
            not liable for decisions you make based on it.
          </p>
        </section>

        <section className="flex flex-col gap-2">
          <h2 className="text-base font-semibold text-foreground">Subscriptions and billing</h2>
          <p>
            The initial assessment and top match are free. Full results, your roadmap, and the AI career advisor
            require a paid subscription ($9/month or $79/year, as shown at checkout). Subscriptions renew
            automatically until canceled. Payments are processed by Stripe. We don&rsquo;t store your card
            details. You can cancel anytime from your account&rsquo;s billing portal; cancellation stops future
            renewals, and you&rsquo;ll keep access through the end of the period you already paid for. We don&rsquo;t
            provide refunds for partial billing periods, except where required by law or at our discretion.
          </p>
        </section>

        <section className="flex flex-col gap-2">
          <h2 className="text-base font-semibold text-foreground">Acceptable use</h2>
          <p>You agree not to:</p>
          <ul className="flex flex-col gap-1.5 pl-4">
            <li className="list-disc">Use the service for anything illegal or to harm others</li>
            <li className="list-disc">Attempt to scrape, reverse-engineer, or extract our occupation data or underlying models in bulk</li>
            <li className="list-disc">Share your account or resell access to the service</li>
            <li className="list-disc">Attempt to disrupt or overload the service</li>
          </ul>
        </section>

        <section className="flex flex-col gap-2">
          <h2 className="text-base font-semibold text-foreground">Your account</h2>
          <p>
            You&rsquo;re responsible for keeping access to your email (since we use passwordless sign-in) secure.
            You can request deletion of your account and data at any time. See our Privacy Policy for how.
          </p>
        </section>

        <section className="flex flex-col gap-2">
          <h2 className="text-base font-semibold text-foreground">Intellectual property</h2>
          <p>
            Vocateur&rsquo;s content, design, and underlying technology belong to us. Your own assessment
            responses and generated results are yours to use personally. You&rsquo;re welcome to download
            and share your own roadmap.
          </p>
        </section>

        <section className="flex flex-col gap-2">
          <h2 className="text-base font-semibold text-foreground">Limitation of liability</h2>
          <p>
            Vocateur is provided &ldquo;as is.&rdquo; To the extent permitted by law, we&rsquo;re not liable for
            indirect, incidental, or consequential damages arising from your use of the service, including career,
            financial, or educational decisions made based on your results.
          </p>
        </section>

        <section className="flex flex-col gap-2">
          <h2 className="text-base font-semibold text-foreground">Changes to these terms</h2>
          <p>
            We may update these terms as Vocateur evolves. If we make material changes, we&rsquo;ll update the
            effective date above and, where appropriate, notify you directly.
          </p>
        </section>

        <section className="flex flex-col gap-2">
          <h2 className="text-base font-semibold text-foreground">Contact us</h2>
          <p>
            Questions about these terms?{" "}
            <a href="mailto:vocateurteam@gmail.com" className="underline underline-offset-2 hover:text-foreground">
              vocateurteam@gmail.com
            </a>
          </p>
        </section>
      </div>
    </main>
  );
}
