// Draft occupation dataset — one-time LLM-assisted trait-profile pass.
// trait_profile dimensions (0-1 each):
//   quadrant_a: analytical/quantitative (Financial Analyst archetype)
//   quadrant_b: sequential/structured (ER Physician archetype)
//   quadrant_c: relational/interpersonal (Executive/People Leader archetype)
//   quadrant_d: experimental/big-picture (Startup Founder archetype)
//   pace_preference: 0 = slow/deliberate, 1 = fast/urgent
//   risk_tolerance: 0 = risk-averse, 1 = risk-seeking
//
// Salary/growth figures are approximate, drawn from general knowledge of
// recent BLS/industry ranges — NOT a live pull. Flagged for manual review
// before hard-coding per the build plan's one-time-LLM-pass-then-human-
// review process. Spot-check before launch.
//
// Rebalanced 2026-07-18 per founder direction: primary audience is
// ambitious high schoolers/university students aiming at high-earning,
// "logically advanced" long-term careers (finance, tech, healthcare, law,
// engineering, bioengineering, pharma, consulting). That set is deep and
// wide below. A small, clearly-secondary ALTERNATIVE PATHS section at the
// end covers skilled trades, aviation, hospitality, and similar — present
// for users who genuinely want that, but deliberately not competing for
// coverage with the main set.

//
// Dominance-sharpened 2026-07-18: every trait_profile rewritten so each
// occupation maps to ONE clearly dominant HBDI quadrant (0.85-0.98), per
// founder direction — prior pass had too many occupations with two
// closely-tied quadrant scores, which flattened cosine-similarity match
// results.
export const DATA_AS_OF = "2025-09-01";

export const occupations = [
  // ---------------------------------------------------------------------
  // FINANCE
  // ---------------------------------------------------------------------
  {
    title: "Investment Banking Analyst",
    description: "Builds financial models and pitch materials for M&A deals and capital raises under intense deadline pressure.",
    median_salary: 125000,
    growth_pct: 8,
    education_level: "Bachelor's degree",
    top_skills: ["Financial modeling", "Valuation", "Excel/PowerPoint", "Deal execution"],
    trait_profile: { quadrant_a: 0.93, quadrant_b: 0.5, quadrant_c: 0.2, quadrant_d: 0.15, pace_preference: 0.9, risk_tolerance: 0.5 },
  },
  {
    title: "Private Equity Associate",
    description: "Evaluates and executes buyout investments, working closely with portfolio companies to drive returns.",
    median_salary: 175000,
    growth_pct: 9,
    education_level: "Bachelor's degree (often + IB experience)",
    top_skills: ["LBO modeling", "Due diligence", "Deal sourcing", "Portfolio strategy"],
    trait_profile: { quadrant_a: 0.9, quadrant_b: 0.3, quadrant_c: 0.25, quadrant_d: 0.45, pace_preference: 0.7, risk_tolerance: 0.6 },
  },
  {
    title: "Hedge Fund Analyst",
    description: "Researches investment theses and market inefficiencies to inform active trading strategies.",
    median_salary: 140000,
    growth_pct: 7,
    education_level: "Bachelor's degree",
    top_skills: ["Fundamental research", "Financial modeling", "Market analysis", "Risk/reward assessment"],
    trait_profile: { quadrant_a: 0.93, quadrant_b: 0.25, quadrant_c: 0.15, quadrant_d: 0.5, pace_preference: 0.75, risk_tolerance: 0.7 },
  },
  {
    title: "Equity Research Analyst",
    description: "Publishes in-depth analysis and price targets on public companies for institutional investors.",
    median_salary: 105000,
    growth_pct: 6,
    education_level: "Bachelor's degree (CFA common)",
    top_skills: ["Financial modeling", "Industry analysis", "Report writing", "Valuation"],
    trait_profile: { quadrant_a: 0.93, quadrant_b: 0.5, quadrant_c: 0.2, quadrant_d: 0.2, pace_preference: 0.55, risk_tolerance: 0.4 },
  },
  {
    title: "Quantitative Analyst",
    description: "Builds mathematical models to price securities, manage risk, or drive systematic trading strategies.",
    median_salary: 150000,
    growth_pct: 10,
    education_level: "Master's/Ph.D. (math, stats, or CS)",
    top_skills: ["Stochastic calculus", "Programming (Python/C++)", "Statistical modeling", "Algorithm design"],
    trait_profile: { quadrant_a: 0.97, quadrant_b: 0.25, quadrant_c: 0.05, quadrant_d: 0.4, pace_preference: 0.5, risk_tolerance: 0.45 },
  },
  {
    title: "Sales & Trading Associate",
    description: "Executes trades and manages institutional client relationships in fast-moving public markets.",
    median_salary: 130000,
    growth_pct: 5,
    education_level: "Bachelor's degree",
    top_skills: ["Market execution", "Client relationship management", "Risk assessment", "Composure under pressure"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.25, quadrant_c: 0.85, quadrant_d: 0.5, pace_preference: 0.95, risk_tolerance: 0.75 },
  },
  {
    title: "Wealth Manager / Financial Advisor",
    description: "Builds long-term investment and financial plans for individual clients based on their goals and risk tolerance.",
    median_salary: 99000,
    growth_pct: 13,
    education_level: "Bachelor's degree + CFP",
    top_skills: ["Financial planning", "Relationship building", "Investment strategy", "Client communication"],
    trait_profile: { quadrant_a: 0.45, quadrant_b: 0.3, quadrant_c: 0.88, quadrant_d: 0.2, pace_preference: 0.4, risk_tolerance: 0.35 },
  },
  {
    title: "Corporate Finance Analyst (FP&A)",
    description: "Builds budgets and forecasts, analyzing company performance to guide internal business decisions.",
    median_salary: 87000,
    growth_pct: 7,
    education_level: "Bachelor's degree",
    top_skills: ["Financial forecasting", "Variance analysis", "Excel modeling", "Business partnering"],
    trait_profile: { quadrant_a: 0.88, quadrant_b: 0.5, quadrant_c: 0.3, quadrant_d: 0.15, pace_preference: 0.45, risk_tolerance: 0.25 },
  },
  {
    title: "Risk Analyst (Financial)",
    description: "Identifies and models exposure to market, credit, and operational risk for a bank or asset manager.",
    median_salary: 95000,
    growth_pct: 6,
    education_level: "Bachelor's degree",
    top_skills: ["Risk modeling", "Statistics", "Regulatory knowledge", "Scenario analysis"],
    trait_profile: { quadrant_a: 0.92, quadrant_b: 0.55, quadrant_c: 0.15, quadrant_d: 0.15, pace_preference: 0.4, risk_tolerance: 0.15 },
  },
  {
    title: "Credit Analyst",
    description: "Assesses the creditworthiness of borrowers to guide lending decisions for a bank or credit fund.",
    median_salary: 82000,
    growth_pct: 5,
    education_level: "Bachelor's degree",
    top_skills: ["Financial statement analysis", "Credit risk modeling", "Industry research", "Report writing"],
    trait_profile: { quadrant_a: 0.9, quadrant_b: 0.55, quadrant_c: 0.2, quadrant_d: 0.1, pace_preference: 0.35, risk_tolerance: 0.15 },
  },
  {
    title: "Portfolio Manager",
    description: "Makes final buy/sell decisions across a fund's holdings, balancing return targets against risk limits.",
    median_salary: 165000,
    growth_pct: 6,
    education_level: "Bachelor's degree (CFA common)",
    top_skills: ["Investment strategy", "Risk management", "Decision-making under uncertainty", "Market judgment"],
    trait_profile: { quadrant_a: 0.88, quadrant_b: 0.3, quadrant_c: 0.25, quadrant_d: 0.5, pace_preference: 0.65, risk_tolerance: 0.65 },
  },
  {
    title: "M&A Analyst",
    description: "Supports mergers and acquisitions from valuation through deal close, coordinating across legal, finance, and strategy.",
    median_salary: 115000,
    growth_pct: 8,
    education_level: "Bachelor's degree",
    top_skills: ["Valuation", "Deal structuring", "Due diligence", "Cross-functional coordination"],
    trait_profile: { quadrant_a: 0.88, quadrant_b: 0.55, quadrant_c: 0.3, quadrant_d: 0.25, pace_preference: 0.75, risk_tolerance: 0.5 },
  },
  {
    title: "Chief Financial Officer",
    description: "Owns a company's financial strategy, reporting, and capital decisions at the executive level.",
    median_salary: 245000,
    growth_pct: 6,
    education_level: "Bachelor's/MBA + extensive experience",
    top_skills: ["Financial strategy", "Executive leadership", "Capital allocation", "Board communication"],
    trait_profile: { quadrant_a: 0.85, quadrant_b: 0.3, quadrant_c: 0.5, quadrant_d: 0.25, pace_preference: 0.5, risk_tolerance: 0.4 },
  },
  {
    title: "Real Estate Investment Analyst",
    description: "Evaluates commercial property acquisitions and development deals through financial modeling.",
    median_salary: 98000,
    growth_pct: 7,
    education_level: "Bachelor's degree",
    top_skills: ["Real estate modeling", "Market analysis", "Deal underwriting", "Excel"],
    trait_profile: { quadrant_a: 0.88, quadrant_b: 0.5, quadrant_c: 0.2, quadrant_d: 0.3, pace_preference: 0.5, risk_tolerance: 0.5 },
  },
  {
    title: "Actuary",
    description: "Uses statistics and financial theory to assess risk for insurance, pensions, and investment decisions.",
    median_salary: 120000,
    growth_pct: 22,
    education_level: "Bachelor's degree + actuarial exams",
    top_skills: ["Statistics", "Risk modeling", "Probability", "Programming"],
    trait_profile: { quadrant_a: 0.97, quadrant_b: 0.5, quadrant_c: 0.1, quadrant_d: 0.15, pace_preference: 0.3, risk_tolerance: 0.15 },
  },
  {
    title: "Public Accountant / Auditor",
    description: "Prepares and examines financial records at a public accounting firm, ensuring accuracy and regulatory compliance.",
    median_salary: 82000,
    growth_pct: 4,
    education_level: "Bachelor's degree + CPA",
    top_skills: ["GAAP", "Attention to detail", "Excel", "Regulatory compliance"],
    trait_profile: { quadrant_a: 0.5, quadrant_b: 0.92, quadrant_c: 0.15, quadrant_d: 0.05, pace_preference: 0.35, risk_tolerance: 0.1 },
  },
  {
    title: "Economist",
    description: "Studies production and distribution of resources, forecasts trends, and advises on policy or business strategy.",
    median_salary: 115730,
    growth_pct: 5,
    education_level: "Master's degree",
    top_skills: ["Econometrics", "Statistical modeling", "Research", "Writing"],
    trait_profile: { quadrant_a: 0.9, quadrant_b: 0.3, quadrant_c: 0.25, quadrant_d: 0.4, pace_preference: 0.3, risk_tolerance: 0.2 },
  },
  {
    title: "Compliance Officer",
    description: "Ensures organizational adherence to financial and legal regulations through structured audits and policy enforcement.",
    median_salary: 88000,
    growth_pct: 5,
    education_level: "Bachelor's degree",
    top_skills: ["Regulatory knowledge", "Audit procedure", "Policy writing", "Attention to detail"],
    trait_profile: { quadrant_a: 0.5, quadrant_b: 0.92, quadrant_c: 0.3, quadrant_d: 0.05, pace_preference: 0.35, risk_tolerance: 0.1 },
  },
  {
    title: "Treasury Analyst",
    description: "Manages a company's cash, liquidity, and financial risk to keep operations funded and protected.",
    median_salary: 84000,
    growth_pct: 6,
    education_level: "Bachelor's degree",
    top_skills: ["Cash management", "Financial risk analysis", "Forecasting", "Banking relationships"],
    trait_profile: { quadrant_a: 0.85, quadrant_b: 0.5, quadrant_c: 0.3, quadrant_d: 0.15, pace_preference: 0.45, risk_tolerance: 0.2 },
  },

  // ---------------------------------------------------------------------
  // TECH / SOFTWARE / COMPUTER
  // ---------------------------------------------------------------------
  {
    title: "Software Engineer",
    description: "Designs, builds, and debugs software systems, balancing structured logic with creative problem-solving.",
    median_salary: 130160,
    growth_pct: 17,
    education_level: "Bachelor's degree",
    top_skills: ["Programming", "Systems thinking", "Debugging", "Algorithm design"],
    trait_profile: { quadrant_a: 0.88, quadrant_b: 0.3, quadrant_c: 0.15, quadrant_d: 0.45, pace_preference: 0.45, risk_tolerance: 0.35 },
  },
  {
    title: "Machine Learning Engineer",
    description: "Builds and deploys models that let software learn from data, from research prototypes to production systems.",
    median_salary: 155000,
    growth_pct: 26,
    education_level: "Bachelor's/Master's degree",
    top_skills: ["Machine learning", "Python", "Model deployment", "Statistics"],
    trait_profile: { quadrant_a: 0.92, quadrant_b: 0.3, quadrant_c: 0.1, quadrant_d: 0.5, pace_preference: 0.5, risk_tolerance: 0.45 },
  },
  {
    title: "AI Research Scientist",
    description: "Pushes the boundary of what machine learning can do, publishing and prototyping novel model architectures.",
    median_salary: 175000,
    growth_pct: 23,
    education_level: "Ph.D. (or exceptional Master's)",
    top_skills: ["Deep learning theory", "Research methodology", "Programming", "Mathematical reasoning"],
    trait_profile: { quadrant_a: 0.95, quadrant_b: 0.25, quadrant_c: 0.1, quadrant_d: 0.55, pace_preference: 0.35, risk_tolerance: 0.55 },
  },
  {
    title: "Data Engineer",
    description: "Builds the pipelines and infrastructure that move and clean data so analysts and models can use it reliably.",
    median_salary: 128000,
    growth_pct: 21,
    education_level: "Bachelor's degree",
    top_skills: ["Data pipelines", "SQL", "Distributed systems", "Cloud infrastructure"],
    trait_profile: { quadrant_a: 0.85, quadrant_b: 0.5, quadrant_c: 0.1, quadrant_d: 0.25, pace_preference: 0.45, risk_tolerance: 0.25 },
  },
  {
    title: "DevOps / Site Reliability Engineer",
    description: "Keeps production systems running, automating deployment and responding to outages under pressure.",
    median_salary: 132000,
    growth_pct: 15,
    education_level: "Bachelor's degree",
    top_skills: ["Cloud infrastructure", "Automation", "Incident response", "Systems monitoring"],
    trait_profile: { quadrant_a: 0.55, quadrant_b: 0.9, quadrant_c: 0.15, quadrant_d: 0.2, pace_preference: 0.8, risk_tolerance: 0.3 },
  },
  {
    title: "Cloud Solutions Architect",
    description: "Designs large-scale cloud infrastructure that balances cost, reliability, and performance for a business.",
    median_salary: 145000,
    growth_pct: 15,
    education_level: "Bachelor's degree",
    top_skills: ["Cloud platforms (AWS/Azure/GCP)", "Systems architecture", "Cost optimization", "Technical communication"],
    trait_profile: { quadrant_a: 0.85, quadrant_b: 0.5, quadrant_c: 0.3, quadrant_d: 0.3, pace_preference: 0.45, risk_tolerance: 0.3 },
  },
  {
    title: "Computer Vision Engineer",
    description: "Builds systems that let machines interpret images and video, from research to real-world deployment.",
    median_salary: 148000,
    growth_pct: 20,
    education_level: "Bachelor's/Master's degree",
    top_skills: ["Computer vision", "Deep learning", "Python/C++", "Mathematical modeling"],
    trait_profile: { quadrant_a: 0.92, quadrant_b: 0.3, quadrant_c: 0.1, quadrant_d: 0.5, pace_preference: 0.45, risk_tolerance: 0.4 },
  },
  {
    title: "Robotics Engineer",
    description: "Designs and programs robotic systems that sense, decide, and act in the physical world.",
    median_salary: 108000,
    growth_pct: 12,
    education_level: "Bachelor's/Master's degree",
    top_skills: ["Controls engineering", "Programming", "Mechanical design", "Systems integration"],
    trait_profile: { quadrant_a: 0.88, quadrant_b: 0.25, quadrant_c: 0.1, quadrant_d: 0.45, pace_preference: 0.4, risk_tolerance: 0.35 },
  },
  {
    title: "Blockchain Developer",
    description: "Builds decentralized applications and smart contracts on emerging, fast-changing infrastructure.",
    median_salary: 135000,
    growth_pct: 12,
    education_level: "Bachelor's degree",
    top_skills: ["Smart contracts", "Cryptography basics", "Programming", "Distributed systems"],
    trait_profile: { quadrant_a: 0.5, quadrant_b: 0.2, quadrant_c: 0.15, quadrant_d: 0.88, pace_preference: 0.5, risk_tolerance: 0.7 },
  },
  {
    title: "Cybersecurity Analyst",
    description: "Monitors and defends systems against threats, following incident-response protocol under time pressure.",
    median_salary: 124910,
    growth_pct: 33,
    education_level: "Bachelor's degree",
    top_skills: ["Threat analysis", "Incident response protocol", "Systems thinking", "Rapid triage"],
    trait_profile: { quadrant_a: 0.88, quadrant_b: 0.5, quadrant_c: 0.15, quadrant_d: 0.25, pace_preference: 0.7, risk_tolerance: 0.3 },
  },
  {
    title: "Mobile App Developer",
    description: "Builds native or cross-platform apps that millions of people might use directly on their phones.",
    median_salary: 118000,
    growth_pct: 14,
    education_level: "Bachelor's degree",
    top_skills: ["Mobile frameworks", "UI implementation", "Programming", "Performance optimization"],
    trait_profile: { quadrant_a: 0.85, quadrant_b: 0.3, quadrant_c: 0.15, quadrant_d: 0.45, pace_preference: 0.5, risk_tolerance: 0.4 },
  },
  {
    title: "IT / Technology Consultant",
    description: "Advises companies on technology strategy and implementation, translating business needs into technical plans.",
    median_salary: 100000,
    growth_pct: 11,
    education_level: "Bachelor's degree",
    top_skills: ["Technical strategy", "Client communication", "Systems analysis", "Project management"],
    trait_profile: { quadrant_a: 0.5, quadrant_b: 0.3, quadrant_c: 0.85, quadrant_d: 0.25, pace_preference: 0.6, risk_tolerance: 0.4 },
  },
  {
    title: "Technical Program Manager",
    description: "Coordinates complex, multi-team engineering efforts, keeping ambiguous technical projects on track.",
    median_salary: 138000,
    growth_pct: 10,
    education_level: "Bachelor's degree",
    top_skills: ["Cross-functional coordination", "Technical fluency", "Risk management", "Prioritization"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.85, quadrant_c: 0.5, quadrant_d: 0.25, pace_preference: 0.6, risk_tolerance: 0.35 },
  },
  {
    title: "Data Architect / DBA",
    description: "Designs how an organization's data is structured, stored, and secured at scale.",
    median_salary: 133000,
    growth_pct: 9,
    education_level: "Bachelor's degree",
    top_skills: ["Database design", "Data modeling", "Systems architecture", "Security"],
    trait_profile: { quadrant_a: 0.88, quadrant_b: 0.5, quadrant_c: 0.1, quadrant_d: 0.25, pace_preference: 0.35, risk_tolerance: 0.2 },
  },
  {
    title: "Network Engineer",
    description: "Designs and maintains the infrastructure that keeps an organization's systems connected and online.",
    median_salary: 95000,
    growth_pct: 6,
    education_level: "Bachelor's degree",
    top_skills: ["Network architecture", "Troubleshooting", "Security protocols", "Systems monitoring"],
    trait_profile: { quadrant_a: 0.5, quadrant_b: 0.88, quadrant_c: 0.15, quadrant_d: 0.15, pace_preference: 0.55, risk_tolerance: 0.2 },
  },
  {
    title: "Data Scientist",
    description: "Builds statistical models and machine learning systems to extract insight and drive product/business decisions.",
    median_salary: 108020,
    growth_pct: 36,
    education_level: "Bachelor's/Master's degree",
    top_skills: ["Statistics", "Python/R", "Machine learning", "Data visualization"],
    trait_profile: { quadrant_a: 0.9, quadrant_b: 0.3, quadrant_c: 0.2, quadrant_d: 0.5, pace_preference: 0.5, risk_tolerance: 0.4 },
  },
  {
    title: "Product Manager (Tech)",
    description: "Defines product strategy and roadmap under ambiguity, synthesizing user, business, and technical constraints.",
    median_salary: 133000,
    growth_pct: 10,
    education_level: "Bachelor's degree",
    top_skills: ["Prioritization under ambiguity", "Cross-functional communication", "Strategic synthesis", "User empathy"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.25, quadrant_c: 0.5, quadrant_d: 0.88, pace_preference: 0.6, risk_tolerance: 0.6 },
  },
  {
    title: "UX / Product Designer",
    description: "Explores open-ended design problems to invent new interaction models and experiences for users.",
    median_salary: 92150,
    growth_pct: 8,
    education_level: "Bachelor's degree",
    top_skills: ["Creative ideation", "User research", "Prototyping", "Visual design"],
    trait_profile: { quadrant_a: 0.2, quadrant_b: 0.2, quadrant_c: 0.5, quadrant_d: 0.9, pace_preference: 0.5, risk_tolerance: 0.55 },
  },
  {
    title: "Game Designer",
    description: "Invents rules, mechanics, and player experiences from scratch, iterating through open-ended prototyping.",
    median_salary: 89410,
    growth_pct: 8,
    education_level: "Bachelor's degree",
    top_skills: ["Systems design", "Creative ideation", "Prototyping", "Playtesting iteration"],
    trait_profile: { quadrant_a: 0.45, quadrant_b: 0.25, quadrant_c: 0.25, quadrant_d: 0.92, pace_preference: 0.5, risk_tolerance: 0.55 },
  },
  {
    title: "Statistician",
    description: "Designs studies and analyzes data to draw statistically valid conclusions across research or business contexts.",
    median_salary: 104100,
    growth_pct: 33,
    education_level: "Master's degree",
    top_skills: ["Statistical modeling", "Study design", "Programming (R/Python)", "Data interpretation"],
    trait_profile: { quadrant_a: 0.96, quadrant_b: 0.5, quadrant_c: 0.15, quadrant_d: 0.25, pace_preference: 0.3, risk_tolerance: 0.2 },
  },
  {
    title: "Growth Product Manager",
    description: "Runs open-ended experiments to find what actually moves a product's growth, with no fixed playbook for what will work.",
    median_salary: 140000,
    growth_pct: 11,
    education_level: "Bachelor's degree",
    top_skills: ["Experimentation", "Data-driven creativity", "Prioritization under ambiguity", "Cross-functional influence"],
    trait_profile: { quadrant_a: 0.5, quadrant_b: 0.2, quadrant_c: 0.3, quadrant_d: 0.9, pace_preference: 0.7, risk_tolerance: 0.65 },
  },
  {
    title: "Startup CTO / Technical Co-Founder",
    description: "Builds a company's entire technical foundation from nothing, making irreversible architecture bets under real uncertainty.",
    median_salary: 160000,
    growth_pct: 12,
    education_level: "Bachelor's degree (often + startup/eng experience)",
    top_skills: ["Systems architecture", "Technical leadership", "Resourcefulness", "Risk tolerance"],
    trait_profile: { quadrant_a: 0.5, quadrant_b: 0.15, quadrant_c: 0.3, quadrant_d: 0.92, pace_preference: 0.75, risk_tolerance: 0.9 },
  },

  // ---------------------------------------------------------------------
  // HEALTHCARE / MEDICINE
  // ---------------------------------------------------------------------
  {
    title: "Emergency Medicine Physician",
    description: "Diagnoses and treats acute illness and injury under time pressure in a hospital emergency department.",
    median_salary: 310640,
    growth_pct: 4,
    education_level: "M.D./D.O. + residency",
    top_skills: ["Triage", "Clinical protocol", "Rapid decision-making", "Procedural skill"],
    trait_profile: { quadrant_a: 0.5, quadrant_b: 0.95, quadrant_c: 0.25, quadrant_d: 0.15, pace_preference: 0.95, risk_tolerance: 0.4 },
  },
  {
    title: "Surgeon",
    description: "Performs operative procedures following strict clinical protocol, often under significant time pressure.",
    median_salary: 297800,
    growth_pct: 4,
    education_level: "M.D. + surgical residency",
    top_skills: ["Procedural precision", "Protocol adherence", "Composure under pressure", "Manual dexterity"],
    trait_profile: { quadrant_a: 0.5, quadrant_b: 0.95, quadrant_c: 0.2, quadrant_d: 0.1, pace_preference: 0.75, risk_tolerance: 0.3 },
  },
  {
    title: "Cardiologist",
    description: "Diagnoses and treats heart conditions, combining deep diagnostic reasoning with long-term patient relationships.",
    median_salary: 353970,
    growth_pct: 4,
    education_level: "M.D./D.O. + cardiology fellowship",
    top_skills: ["Diagnostic reasoning", "Clinical protocol", "Patient communication", "Procedural skill"],
    trait_profile: { quadrant_a: 0.85, quadrant_b: 0.3, quadrant_c: 0.5, quadrant_d: 0.15, pace_preference: 0.55, risk_tolerance: 0.25 },
  },
  {
    title: "Anesthesiologist",
    description: "Manages patient sedation and vital functions during surgery, requiring constant vigilance and split-second judgment.",
    median_salary: 331190,
    growth_pct: 3,
    education_level: "M.D./D.O. + residency",
    top_skills: ["Pharmacology", "Real-time monitoring", "Composure under pressure", "Procedural precision"],
    trait_profile: { quadrant_a: 0.5, quadrant_b: 0.92, quadrant_c: 0.2, quadrant_d: 0.1, pace_preference: 0.8, risk_tolerance: 0.25 },
  },
  {
    title: "Radiologist",
    description: "Interprets medical imaging to diagnose disease, working through large volumes of complex visual data.",
    median_salary: 349000,
    growth_pct: 4,
    education_level: "M.D./D.O. + residency",
    top_skills: ["Image interpretation", "Diagnostic reasoning", "Attention to detail", "Pattern recognition"],
    trait_profile: { quadrant_a: 0.9, quadrant_b: 0.5, quadrant_c: 0.1, quadrant_d: 0.15, pace_preference: 0.55, risk_tolerance: 0.2 },
  },
  {
    title: "Dermatologist",
    description: "Diagnoses and treats skin conditions, blending clinical precision with a steady, appointment-driven pace.",
    median_salary: 341000,
    growth_pct: 4,
    education_level: "M.D./D.O. + residency",
    top_skills: ["Diagnostic reasoning", "Procedural skill", "Patient communication", "Attention to detail"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.85, quadrant_c: 0.5, quadrant_d: 0.15, pace_preference: 0.45, risk_tolerance: 0.2 },
  },
  {
    title: "Oncologist",
    description: "Diagnoses and manages cancer treatment, combining rigorous protocol with deeply personal patient relationships.",
    median_salary: 330000,
    growth_pct: 5,
    education_level: "M.D./D.O. + oncology fellowship",
    top_skills: ["Clinical protocol", "Treatment planning", "Patient communication", "Emotional resilience"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.85, quadrant_c: 0.5, quadrant_d: 0.15, pace_preference: 0.5, risk_tolerance: 0.25 },
  },
  {
    title: "Pediatrician",
    description: "Provides primary care for children, balancing clinical protocol with patient and family relationships.",
    median_salary: 198420,
    growth_pct: 4,
    education_level: "M.D./D.O. + residency",
    top_skills: ["Clinical diagnosis", "Patient/family communication", "Protocol adherence", "Patience"],
    trait_profile: { quadrant_a: 0.25, quadrant_b: 0.5, quadrant_c: 0.85, quadrant_d: 0.1, pace_preference: 0.5, risk_tolerance: 0.2 },
  },
  {
    title: "Psychiatrist",
    description: "Diagnoses and treats mental health conditions through a mix of clinical protocol, medication, and therapy.",
    median_salary: 245000,
    growth_pct: 8,
    education_level: "M.D./D.O. + psychiatry residency",
    top_skills: ["Clinical assessment", "Active listening", "Treatment planning", "Pharmacology"],
    trait_profile: { quadrant_a: 0.25, quadrant_b: 0.5, quadrant_c: 0.9, quadrant_d: 0.15, pace_preference: 0.35, risk_tolerance: 0.2 },
  },
  {
    title: "Orthopedic Surgeon",
    description: "Repairs bones, joints, and muscles through surgery, requiring precision under significant physical demand.",
    median_salary: 375000,
    growth_pct: 4,
    education_level: "M.D./D.O. + surgical residency",
    top_skills: ["Surgical precision", "Protocol adherence", "Physical stamina", "Diagnostic reasoning"],
    trait_profile: { quadrant_a: 0.5, quadrant_b: 0.92, quadrant_c: 0.25, quadrant_d: 0.1, pace_preference: 0.65, risk_tolerance: 0.3 },
  },
  {
    title: "Neurologist",
    description: "Diagnoses and treats disorders of the brain and nervous system through careful, methodical reasoning.",
    median_salary: 280000,
    growth_pct: 5,
    education_level: "M.D./D.O. + neurology residency",
    top_skills: ["Diagnostic reasoning", "Neuroanatomy", "Patient communication", "Pattern recognition"],
    trait_profile: { quadrant_a: 0.88, quadrant_b: 0.5, quadrant_c: 0.3, quadrant_d: 0.15, pace_preference: 0.4, risk_tolerance: 0.2 },
  },
  {
    title: "Physician Assistant",
    description: "Diagnoses and treats patients under physician supervision, often serving as a patient's primary point of contact.",
    median_salary: 130020,
    growth_pct: 27,
    education_level: "Master's degree (PA program)",
    top_skills: ["Clinical assessment", "Protocol adherence", "Patient communication", "Multitasking"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.85, quadrant_c: 0.5, quadrant_d: 0.1, pace_preference: 0.65, risk_tolerance: 0.25 },
  },
  {
    title: "Nurse Practitioner",
    description: "Provides advanced primary and specialty care, often with the autonomy to diagnose and prescribe independently.",
    median_salary: 129480,
    growth_pct: 40,
    education_level: "Master's/Doctorate (DNP)",
    top_skills: ["Clinical diagnosis", "Patient communication", "Protocol adherence", "Independent judgment"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.85, quadrant_c: 0.5, quadrant_d: 0.15, pace_preference: 0.6, risk_tolerance: 0.25 },
  },
  {
    title: "Registered Nurse",
    description: "Provides direct patient care, administers treatment, and coordinates with physicians under clinical protocol.",
    median_salary: 86070,
    growth_pct: 6,
    education_level: "Bachelor's/Associate degree + license",
    top_skills: ["Clinical care", "Protocol adherence", "Patient communication", "Multitasking"],
    trait_profile: { quadrant_a: 0.2, quadrant_b: 0.5, quadrant_c: 0.85, quadrant_d: 0.1, pace_preference: 0.75, risk_tolerance: 0.2 },
  },
  {
    title: "Dentist",
    description: "Diagnoses and treats oral health conditions in a structured, appointment-driven clinical practice.",
    median_salary: 174420,
    growth_pct: 5,
    education_level: "D.D.S./D.M.D.",
    top_skills: ["Procedural precision", "Diagnostic reasoning", "Patient communication", "Manual dexterity"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.88, quadrant_c: 0.5, quadrant_d: 0.1, pace_preference: 0.5, risk_tolerance: 0.2 },
  },
  {
    title: "Orthodontist",
    description: "Corrects teeth and jaw alignment through long-term, carefully sequenced treatment plans.",
    median_salary: 251000,
    growth_pct: 5,
    education_level: "D.D.S./D.M.D. + orthodontic residency",
    top_skills: ["Treatment planning", "Procedural precision", "Patient communication", "Long-term case management"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.9, quadrant_c: 0.45, quadrant_d: 0.1, pace_preference: 0.4, risk_tolerance: 0.15 },
  },
  {
    title: "Pharmacist",
    description: "Dispenses medication, verifies dosage safety, and advises patients following strict regulatory protocol.",
    median_salary: 136030,
    growth_pct: 3,
    education_level: "Pharm.D. degree",
    top_skills: ["Pharmacology", "Protocol verification", "Attention to detail", "Patient counseling"],
    trait_profile: { quadrant_a: 0.45, quadrant_b: 0.92, quadrant_c: 0.3, quadrant_d: 0.05, pace_preference: 0.5, risk_tolerance: 0.1 },
  },
  {
    title: "Physical Therapist",
    description: "Designs and delivers rehabilitation plans following clinical protocol, adjusting to each patient's progress.",
    median_salary: 99710,
    growth_pct: 14,
    education_level: "Doctorate (DPT)",
    top_skills: ["Clinical assessment", "Treatment planning", "Patient communication", "Anatomy knowledge"],
    trait_profile: { quadrant_a: 0.25, quadrant_b: 0.5, quadrant_c: 0.85, quadrant_d: 0.15, pace_preference: 0.45, risk_tolerance: 0.2 },
  },
  {
    title: "Occupational Therapist",
    description: "Helps patients regain daily living skills through individualized, protocol-guided therapeutic plans.",
    median_salary: 96370,
    growth_pct: 11,
    education_level: "Master's/Doctorate degree",
    top_skills: ["Patient assessment", "Treatment planning", "Empathy", "Adaptive problem-solving"],
    trait_profile: { quadrant_a: 0.2, quadrant_b: 0.5, quadrant_c: 0.85, quadrant_d: 0.15, pace_preference: 0.4, risk_tolerance: 0.15 },
  },
  {
    title: "Genetic Counselor",
    description: "Interprets genetic testing and helps patients understand hereditary health risks and options.",
    median_salary: 95000,
    growth_pct: 16,
    education_level: "Master's degree",
    top_skills: ["Genetics knowledge", "Patient counseling", "Risk communication", "Empathy"],
    trait_profile: { quadrant_a: 0.45, quadrant_b: 0.3, quadrant_c: 0.85, quadrant_d: 0.15, pace_preference: 0.35, risk_tolerance: 0.15 },
  },
  {
    title: "Epidemiologist / Public Health Analyst",
    description: "Studies disease patterns and public health data to inform policy and prevention strategy.",
    median_salary: 82000,
    growth_pct: 27,
    education_level: "Master's degree (MPH)",
    top_skills: ["Statistical analysis", "Study design", "Public health policy", "Data interpretation"],
    trait_profile: { quadrant_a: 0.9, quadrant_b: 0.5, quadrant_c: 0.15, quadrant_d: 0.3, pace_preference: 0.35, risk_tolerance: 0.25 },
  },
  {
    title: "Healthcare Consultant",
    description: "Advises hospitals and health systems on strategy, operations, and efficiency improvements.",
    median_salary: 108000,
    growth_pct: 10,
    education_level: "Bachelor's/MBA",
    top_skills: ["Healthcare operations", "Strategic analysis", "Client communication", "Data-driven problem-solving"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.2, quadrant_c: 0.5, quadrant_d: 0.85, pace_preference: 0.6, risk_tolerance: 0.4 },
  },
  {
    title: "Hospital Administrator",
    description: "Manages the operations, budget, and staff of a hospital or healthcare system.",
    median_salary: 118000,
    growth_pct: 28,
    education_level: "Master's degree (MHA/MBA)",
    top_skills: ["Operations management", "Budgeting", "Team leadership", "Regulatory knowledge"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.85, quadrant_c: 0.5, quadrant_d: 0.2, pace_preference: 0.55, risk_tolerance: 0.3 },
  },
  {
    title: "Concierge Medicine Physician",
    description: "Provides highly personalized, relationship-first primary care to a small panel of patients who pay directly for access.",
    median_salary: 260000,
    growth_pct: 8,
    education_level: "M.D./D.O. + residency",
    top_skills: ["Patient relationship-building", "Clinical judgment", "Communication", "Personalized care planning"],
    trait_profile: { quadrant_a: 0.45, quadrant_b: 0.3, quadrant_c: 0.92, quadrant_d: 0.15, pace_preference: 0.35, risk_tolerance: 0.3 },
  },
  {
    title: "Major Gifts / Philanthropy Officer",
    description: "Builds relationships with high-net-worth donors to fund a university, hospital, or nonprofit's biggest initiatives.",
    median_salary: 105000,
    growth_pct: 9,
    education_level: "Bachelor's degree",
    top_skills: ["Relationship building", "Persuasive storytelling", "Networking", "Long-term trust-building"],
    trait_profile: { quadrant_a: 0.15, quadrant_b: 0.25, quadrant_c: 0.92, quadrant_d: 0.45, pace_preference: 0.4, risk_tolerance: 0.4 },
  },
  {
    title: "Client Success Director (SaaS/Tech)",
    description: "Owns the relationship with a tech company's biggest customers, making sure they get value and stay.",
    median_salary: 135000,
    growth_pct: 12,
    education_level: "Bachelor's degree",
    top_skills: ["Relationship management", "Problem-solving", "Cross-functional advocacy", "Communication"],
    trait_profile: { quadrant_a: 0.45, quadrant_b: 0.3, quadrant_c: 0.88, quadrant_d: 0.2, pace_preference: 0.55, risk_tolerance: 0.35 },
  },
  {
    title: "Behavioral / Clinical Psychologist",
    description: "Assesses and treats mental health conditions through structured therapeutic frameworks and deep interpersonal work.",
    median_salary: 92740,
    growth_pct: 7,
    education_level: "Doctorate (Ph.D./Psy.D.)",
    top_skills: ["Clinical assessment", "Active listening", "Treatment planning", "Empathy"],
    trait_profile: { quadrant_a: 0.25, quadrant_b: 0.5, quadrant_c: 0.92, quadrant_d: 0.15, pace_preference: 0.3, risk_tolerance: 0.15 },
  },
  {
    title: "Family Medicine Physician",
    description: "Provides ongoing primary care across a patient's life, building long-term relationships more than any single specialty.",
    median_salary: 245000,
    growth_pct: 4,
    education_level: "M.D./D.O. + residency",
    top_skills: ["Patient relationship-building", "Broad clinical knowledge", "Communication", "Continuity of care"],
    trait_profile: { quadrant_a: 0.25, quadrant_b: 0.5, quadrant_c: 0.88, quadrant_d: 0.15, pace_preference: 0.45, risk_tolerance: 0.2 },
  },

  // ---------------------------------------------------------------------
  // LAW
  // ---------------------------------------------------------------------
  {
    title: "Litigation Attorney",
    description: "Builds and argues legal cases, combining rigorous procedural preparation with adversarial persuasion.",
    median_salary: 145760,
    growth_pct: 5,
    education_level: "J.D. + bar admission",
    top_skills: ["Legal research", "Argumentation", "Procedural discipline", "Persuasive writing"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.85, quadrant_c: 0.5, quadrant_d: 0.15, pace_preference: 0.6, risk_tolerance: 0.4 },
  },
  {
    title: "Corporate Lawyer (Transactional)",
    description: "Structures deals and contracts, balancing precise procedural drafting with client relationship management.",
    median_salary: 145760,
    growth_pct: 5,
    education_level: "J.D. + bar admission",
    top_skills: ["Contract drafting", "Negotiation", "Regulatory knowledge", "Client management"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.88, quadrant_c: 0.5, quadrant_d: 0.1, pace_preference: 0.45, risk_tolerance: 0.25 },
  },
  {
    title: "Intellectual Property / Patent Attorney",
    description: "Protects inventions and creative work through patent filings and IP litigation, often requiring a technical background.",
    median_salary: 165000,
    growth_pct: 6,
    education_level: "J.D. + technical Bachelor's degree",
    top_skills: ["Patent law", "Technical analysis", "Legal writing", "Attention to detail"],
    trait_profile: { quadrant_a: 0.85, quadrant_b: 0.5, quadrant_c: 0.25, quadrant_d: 0.2, pace_preference: 0.45, risk_tolerance: 0.25 },
  },
  {
    title: "Tax Attorney",
    description: "Advises individuals and companies on complex tax law and represents them in disputes with tax authorities.",
    median_salary: 155000,
    growth_pct: 5,
    education_level: "J.D. + often LL.M. in Taxation",
    top_skills: ["Tax law", "Legal research", "Analytical reasoning", "Client advising"],
    trait_profile: { quadrant_a: 0.88, quadrant_b: 0.5, quadrant_c: 0.25, quadrant_d: 0.1, pace_preference: 0.4, risk_tolerance: 0.15 },
  },
  {
    title: "Mergers & Acquisitions Lawyer",
    description: "Structures and negotiates the legal terms of company acquisitions and mergers under significant deal pressure.",
    median_salary: 195000,
    growth_pct: 6,
    education_level: "J.D. + bar admission",
    top_skills: ["Deal structuring", "Negotiation", "Contract law", "Due diligence"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.85, quadrant_c: 0.5, quadrant_d: 0.2, pace_preference: 0.75, risk_tolerance: 0.4 },
  },
  {
    title: "In-House Corporate Counsel",
    description: "Serves as a company's internal legal advisor, balancing legal risk against business goals day to day.",
    median_salary: 155000,
    growth_pct: 6,
    education_level: "J.D. + bar admission",
    top_skills: ["Legal risk assessment", "Contract review", "Business partnering", "Pragmatic judgment"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.85, quadrant_c: 0.5, quadrant_d: 0.2, pace_preference: 0.5, risk_tolerance: 0.3 },
  },
  {
    title: "Regulatory / Compliance Attorney",
    description: "Ensures a company's practices meet complex, evolving legal and regulatory requirements.",
    median_salary: 148000,
    growth_pct: 6,
    education_level: "J.D. + bar admission",
    top_skills: ["Regulatory analysis", "Policy interpretation", "Risk assessment", "Legal writing"],
    trait_profile: { quadrant_a: 0.5, quadrant_b: 0.92, quadrant_c: 0.2, quadrant_d: 0.05, pace_preference: 0.4, risk_tolerance: 0.15 },
  },

  // ---------------------------------------------------------------------
  // ENGINEERING
  // ---------------------------------------------------------------------
  {
    title: "Mechanical Engineer",
    description: "Designs and tests mechanical systems and products following engineering standards and iterative prototyping.",
    median_salary: 99510,
    growth_pct: 7,
    education_level: "Bachelor's degree",
    top_skills: ["CAD", "Thermodynamics", "Prototyping", "Problem-solving"],
    trait_profile: { quadrant_a: 0.88, quadrant_b: 0.28, quadrant_c: 0.12, quadrant_d: 0.45, pace_preference: 0.35, risk_tolerance: 0.3 },
  },
  {
    title: "Electrical Engineer",
    description: "Designs electrical systems and components, from circuits to power infrastructure, following technical standards.",
    median_salary: 109010,
    growth_pct: 5,
    education_level: "Bachelor's degree",
    top_skills: ["Circuit design", "Signal analysis", "Technical documentation", "Testing"],
    trait_profile: { quadrant_a: 0.88, quadrant_b: 0.48, quadrant_c: 0.12, quadrant_d: 0.25, pace_preference: 0.35, risk_tolerance: 0.25 },
  },
  {
    title: "Civil Engineer",
    description: "Designs and oversees infrastructure projects following building codes, safety standards, and structured project phases.",
    median_salary: 95890,
    growth_pct: 5,
    education_level: "Bachelor's degree + P.E. license",
    top_skills: ["Structural analysis", "CAD", "Code compliance", "Project sequencing"],
    trait_profile: { quadrant_a: 0.5, quadrant_b: 0.85, quadrant_c: 0.25, quadrant_d: 0.15, pace_preference: 0.35, risk_tolerance: 0.15 },
  },
  {
    title: "Chemical Engineer",
    description: "Designs industrial chemical processes, scaling reactions safely from lab to full production.",
    median_salary: 112100,
    growth_pct: 6,
    education_level: "Bachelor's degree",
    top_skills: ["Process design", "Thermodynamics", "Safety engineering", "Process optimization"],
    trait_profile: { quadrant_a: 0.88, quadrant_b: 0.5, quadrant_c: 0.12, quadrant_d: 0.25, pace_preference: 0.35, risk_tolerance: 0.2 },
  },
  {
    title: "Aerospace Engineer",
    description: "Designs aircraft and spacecraft systems, working at the edge of what's physically possible.",
    median_salary: 130720,
    growth_pct: 6,
    education_level: "Bachelor's/Master's degree",
    top_skills: ["Aerodynamics", "CAD/simulation", "Systems engineering", "Testing"],
    trait_profile: { quadrant_a: 0.92, quadrant_b: 0.3, quadrant_c: 0.1, quadrant_d: 0.45, pace_preference: 0.3, risk_tolerance: 0.3 },
  },
  {
    title: "Industrial Engineer",
    description: "Optimizes complex systems and processes — factories, supply chains, hospitals — for efficiency and quality.",
    median_salary: 96350,
    growth_pct: 10,
    education_level: "Bachelor's degree",
    top_skills: ["Process optimization", "Statistics", "Systems analysis", "Lean methodology"],
    trait_profile: { quadrant_a: 0.5, quadrant_b: 0.85, quadrant_c: 0.25, quadrant_d: 0.2, pace_preference: 0.45, risk_tolerance: 0.25 },
  },
  {
    title: "Materials Science Engineer",
    description: "Develops new materials with specific properties, from lab research through to industrial application.",
    median_salary: 100090,
    growth_pct: 6,
    education_level: "Bachelor's/Master's degree",
    top_skills: ["Materials characterization", "Research methodology", "Chemistry/physics", "Experimental design"],
    trait_profile: { quadrant_a: 0.93, quadrant_b: 0.3, quadrant_c: 0.1, quadrant_d: 0.45, pace_preference: 0.25, risk_tolerance: 0.3 },
  },
  {
    title: "Environmental Engineer",
    description: "Designs systems and solutions to address pollution, water quality, and environmental regulatory compliance.",
    median_salary: 96820,
    growth_pct: 6,
    education_level: "Bachelor's degree",
    top_skills: ["Environmental regulation", "Systems design", "Data analysis", "Technical writing"],
    trait_profile: { quadrant_a: 0.85, quadrant_b: 0.5, quadrant_c: 0.2, quadrant_d: 0.25, pace_preference: 0.35, risk_tolerance: 0.25 },
  },
  {
    title: "Structural Engineer",
    description: "Ensures buildings and infrastructure can safely bear the loads and forces they'll face over their lifetime.",
    median_salary: 100000,
    growth_pct: 5,
    education_level: "Bachelor's degree + P.E. license",
    top_skills: ["Structural analysis", "CAD", "Code compliance", "Risk assessment"],
    trait_profile: { quadrant_a: 0.5, quadrant_b: 0.9, quadrant_c: 0.12, quadrant_d: 0.1, pace_preference: 0.3, risk_tolerance: 0.1 },
  },
  {
    title: "Petroleum Engineer",
    description: "Designs methods for extracting oil and gas efficiently and safely from reservoirs.",
    median_salary: 135690,
    growth_pct: 2,
    education_level: "Bachelor's degree",
    top_skills: ["Reservoir engineering", "Technical modeling", "Field operations knowledge", "Risk assessment"],
    trait_profile: { quadrant_a: 0.85, quadrant_b: 0.5, quadrant_c: 0.15, quadrant_d: 0.3, pace_preference: 0.45, risk_tolerance: 0.35 },
  },
  {
    title: "Nuclear Engineer",
    description: "Designs and oversees nuclear systems used for power generation or research, under strict safety protocol.",
    median_salary: 129210,
    growth_pct: 6,
    education_level: "Bachelor's/Master's degree",
    top_skills: ["Nuclear physics", "Safety engineering", "Systems analysis", "Regulatory compliance"],
    trait_profile: { quadrant_a: 0.93, quadrant_b: 0.55, quadrant_c: 0.08, quadrant_d: 0.15, pace_preference: 0.3, risk_tolerance: 0.1 },
  },

  // ---------------------------------------------------------------------
  // BIOENGINEERING / BIOTECH
  // ---------------------------------------------------------------------
  {
    title: "Biomedical Engineer",
    description: "Designs medical devices and equipment, combining engineering rigor with an understanding of human biology.",
    median_salary: 100730,
    growth_pct: 5,
    education_level: "Bachelor's/Master's degree",
    top_skills: ["Medical device design", "Biology knowledge", "CAD/prototyping", "Regulatory standards"],
    trait_profile: { quadrant_a: 0.85, quadrant_b: 0.3, quadrant_c: 0.15, quadrant_d: 0.45, pace_preference: 0.35, risk_tolerance: 0.3 },
  },
  {
    title: "Biotech Research Scientist",
    description: "Conducts lab research to develop new therapies and technologies, from early discovery through validation.",
    median_salary: 102270,
    growth_pct: 10,
    education_level: "Ph.D. (or Master's + experience)",
    top_skills: ["Lab protocol", "Experimental design", "Molecular biology", "Scientific writing"],
    trait_profile: { quadrant_a: 0.9, quadrant_b: 0.3, quadrant_c: 0.1, quadrant_d: 0.45, pace_preference: 0.25, risk_tolerance: 0.3 },
  },
  {
    title: "Bioinformatics Scientist",
    description: "Analyzes massive biological datasets — genomes, proteins — using computational methods to drive discovery.",
    median_salary: 118000,
    growth_pct: 15,
    education_level: "Master's/Ph.D.",
    top_skills: ["Computational biology", "Programming", "Statistics", "Genomics"],
    trait_profile: { quadrant_a: 0.95, quadrant_b: 0.3, quadrant_c: 0.08, quadrant_d: 0.4, pace_preference: 0.3, risk_tolerance: 0.25 },
  },
  {
    title: "Genetic Engineer",
    description: "Modifies organisms at the genetic level for medical, agricultural, or industrial applications.",
    median_salary: 108000,
    growth_pct: 9,
    education_level: "Master's/Ph.D.",
    top_skills: ["Molecular biology", "Gene editing techniques", "Lab protocol", "Experimental design"],
    trait_profile: { quadrant_a: 0.9, quadrant_b: 0.3, quadrant_c: 0.08, quadrant_d: 0.5, pace_preference: 0.3, risk_tolerance: 0.35 },
  },
  {
    title: "Clinical Research Associate",
    description: "Monitors clinical trials to ensure they're run safely, ethically, and in compliance with regulation.",
    median_salary: 78000,
    growth_pct: 12,
    education_level: "Bachelor's degree (life sciences)",
    top_skills: ["Clinical trial protocol", "Regulatory compliance", "Attention to detail", "Site coordination"],
    trait_profile: { quadrant_a: 0.5, quadrant_b: 0.9, quadrant_c: 0.3, quadrant_d: 0.08, pace_preference: 0.45, risk_tolerance: 0.15 },
  },
  {
    title: "Regulatory Affairs Specialist (Biotech/Pharma)",
    description: "Guides new drugs and devices through regulatory approval, translating science into compliance strategy.",
    median_salary: 105000,
    growth_pct: 8,
    education_level: "Bachelor's/Master's degree",
    top_skills: ["Regulatory strategy", "Scientific writing", "Compliance", "Cross-functional coordination"],
    trait_profile: { quadrant_a: 0.5, quadrant_b: 0.88, quadrant_c: 0.3, quadrant_d: 0.1, pace_preference: 0.35, risk_tolerance: 0.15 },
  },
  {
    title: "Biomedical Researcher",
    description: "Conducts lab research to advance medical treatment, following rigorous experimental protocol.",
    median_salary: 100890,
    growth_pct: 10,
    education_level: "Ph.D.",
    top_skills: ["Lab protocol", "Statistical analysis", "Experimental design", "Scientific writing"],
    trait_profile: { quadrant_a: 0.92, quadrant_b: 0.5, quadrant_c: 0.1, quadrant_d: 0.3, pace_preference: 0.25, risk_tolerance: 0.25 },
  },

  // ---------------------------------------------------------------------
  // PHARMACEUTICALS
  // ---------------------------------------------------------------------
  {
    title: "Pharmaceutical Scientist",
    description: "Develops and tests new drug formulations, from early discovery through manufacturing readiness.",
    median_salary: 115000,
    growth_pct: 9,
    education_level: "Ph.D. (or Master's + experience)",
    top_skills: ["Drug formulation", "Lab protocol", "Chemistry", "Experimental design"],
    trait_profile: { quadrant_a: 0.92, quadrant_b: 0.5, quadrant_c: 0.1, quadrant_d: 0.3, pace_preference: 0.3, risk_tolerance: 0.25 },
  },
  {
    title: "Clinical Trials / Drug Development Manager",
    description: "Runs the process of testing new drugs in humans, coordinating science, regulation, and operations.",
    median_salary: 135000,
    growth_pct: 10,
    education_level: "Master's degree (life sciences)",
    top_skills: ["Clinical trial design", "Project management", "Regulatory knowledge", "Cross-functional leadership"],
    trait_profile: { quadrant_a: 0.5, quadrant_b: 0.85, quadrant_c: 0.3, quadrant_d: 0.15, pace_preference: 0.5, risk_tolerance: 0.3 },
  },
  {
    title: "Medical Science Liaison",
    description: "Bridges pharmaceutical research and practicing physicians, communicating complex clinical data.",
    median_salary: 155000,
    growth_pct: 8,
    education_level: "Ph.D./Pharm.D./M.D. (or advanced life sciences degree)",
    top_skills: ["Scientific communication", "Relationship building", "Clinical knowledge", "Presentation skills"],
    trait_profile: { quadrant_a: 0.5, quadrant_b: 0.3, quadrant_c: 0.85, quadrant_d: 0.15, pace_preference: 0.5, risk_tolerance: 0.3 },
  },
  {
    title: "Pharmacologist",
    description: "Studies how drugs interact with biological systems to inform safer, more effective treatments.",
    median_salary: 112000,
    growth_pct: 8,
    education_level: "Ph.D.",
    top_skills: ["Pharmacology research", "Experimental design", "Statistical analysis", "Scientific writing"],
    trait_profile: { quadrant_a: 0.94, quadrant_b: 0.5, quadrant_c: 0.08, quadrant_d: 0.25, pace_preference: 0.25, risk_tolerance: 0.25 },
  },

  // ---------------------------------------------------------------------
  // CONSULTING & STRATEGY
  // ---------------------------------------------------------------------
  {
    title: "Management Consultant",
    description: "Diagnoses ambiguous business problems for clients and proposes novel strategic solutions under time pressure.",
    median_salary: 99410,
    growth_pct: 10,
    education_level: "Bachelor's/MBA",
    top_skills: ["Structured problem-solving", "Client communication", "Strategic synthesis", "Adaptability"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.15, quadrant_c: 0.5, quadrant_d: 0.85, pace_preference: 0.7, risk_tolerance: 0.5 },
  },
  {
    title: "Strategy Consultant",
    description: "Advises company leadership on major strategic decisions — market entry, growth, competitive positioning.",
    median_salary: 145000,
    growth_pct: 10,
    education_level: "MBA (or exceptional Bachelor's)",
    top_skills: ["Strategic frameworks", "Executive communication", "Market analysis", "Structured problem-solving"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.15, quadrant_c: 0.5, quadrant_d: 0.85, pace_preference: 0.65, risk_tolerance: 0.55 },
  },
  {
    title: "Economic / Policy Consultant",
    description: "Applies economic analysis to advise governments, corporations, or law firms on policy and litigation matters.",
    median_salary: 118000,
    growth_pct: 8,
    education_level: "Master's degree",
    top_skills: ["Econometrics", "Policy analysis", "Report writing", "Client communication"],
    trait_profile: { quadrant_a: 0.88, quadrant_b: 0.3, quadrant_c: 0.45, quadrant_d: 0.25, pace_preference: 0.4, risk_tolerance: 0.25 },
  },
  {
    title: "Innovation Consultant",
    description: "Helps established companies invent and prototype new business models and products from scratch.",
    median_salary: 128000,
    growth_pct: 11,
    education_level: "Bachelor's/MBA",
    top_skills: ["Design thinking", "Ideation facilitation", "Prototyping", "Ambiguity tolerance"],
    trait_profile: { quadrant_a: 0.25, quadrant_b: 0.1, quadrant_c: 0.48, quadrant_d: 0.93, pace_preference: 0.6, risk_tolerance: 0.7 },
  },

  // ---------------------------------------------------------------------
  // BUSINESS / CORPORATE
  // ---------------------------------------------------------------------
  {
    title: "Chief Executive Officer",
    description: "Sets organizational strategy and culture, resolves cross-functional conflict, and represents the company to stakeholders.",
    median_salary: 206680,
    growth_pct: 6,
    education_level: "Bachelor's/MBA (varies widely)",
    top_skills: ["Strategic vision", "People leadership", "Conflict mediation", "Communication"],
    trait_profile: { quadrant_a: 0.25, quadrant_b: 0.2, quadrant_c: 0.88, quadrant_d: 0.5, pace_preference: 0.6, risk_tolerance: 0.6 },
  },
  {
    title: "Chief Operating Officer",
    description: "Owns the operational execution of a company's strategy, keeping teams and processes running at scale.",
    median_salary: 195000,
    growth_pct: 6,
    education_level: "Bachelor's/MBA + extensive experience",
    top_skills: ["Operations leadership", "Cross-functional coordination", "Process design", "Executive communication"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.85, quadrant_c: 0.5, quadrant_d: 0.2, pace_preference: 0.55, risk_tolerance: 0.4 },
  },
  {
    title: "Human Resources / People Director",
    description: "Leads hiring strategy, employee relations, and organizational culture across a growing company.",
    median_salary: 145000,
    growth_pct: 6,
    education_level: "Bachelor's degree",
    top_skills: ["Conflict resolution", "Empathetic listening", "Policy design", "Negotiation"],
    trait_profile: { quadrant_a: 0.15, quadrant_b: 0.48, quadrant_c: 0.9, quadrant_d: 0.25, pace_preference: 0.45, risk_tolerance: 0.25 },
  },
  {
    title: "Sales Director",
    description: "Leads a company's revenue-generating sales team, resolving client and internal team conflict.",
    median_salary: 140000,
    growth_pct: 5,
    education_level: "Bachelor's degree",
    top_skills: ["Relationship building", "Negotiation", "Team leadership", "Persuasion"],
    trait_profile: { quadrant_a: 0.2, quadrant_b: 0.25, quadrant_c: 0.88, quadrant_d: 0.45, pace_preference: 0.65, risk_tolerance: 0.5 },
  },
  {
    title: "Product Marketing Manager",
    description: "Positions and launches products, translating what's built into a story customers actually want.",
    median_salary: 128000,
    growth_pct: 8,
    education_level: "Bachelor's degree",
    top_skills: ["Positioning strategy", "Cross-functional collaboration", "Storytelling", "Market research"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.2, quadrant_c: 0.5, quadrant_d: 0.85, pace_preference: 0.55, risk_tolerance: 0.5 },
  },
  {
    title: "Brand Manager",
    description: "Owns the strategy and identity of a product or company brand, balancing creative vision with market data.",
    median_salary: 118000,
    growth_pct: 6,
    education_level: "Bachelor's degree",
    top_skills: ["Brand strategy", "Creative direction", "Market analysis", "Cross-team leadership"],
    trait_profile: { quadrant_a: 0.25, quadrant_b: 0.2, quadrant_c: 0.48, quadrant_d: 0.85, pace_preference: 0.5, risk_tolerance: 0.5 },
  },
  {
    title: "Creative Director (Advertising)",
    description: "Leads the creative vision for ad campaigns and brand work, making bold calls with no formula for what will land.",
    median_salary: 145000,
    growth_pct: 6,
    education_level: "Bachelor's degree",
    top_skills: ["Creative vision", "Team leadership", "Client presentation", "Original thinking"],
    trait_profile: { quadrant_a: 0.15, quadrant_b: 0.1, quadrant_c: 0.5, quadrant_d: 0.95, pace_preference: 0.55, risk_tolerance: 0.7 },
  },
  {
    title: "Chief Marketing Officer",
    description: "Sets a company's entire brand and growth strategy at the executive level, betting on unproven creative and market directions.",
    median_salary: 225000,
    growth_pct: 7,
    education_level: "Bachelor's/MBA + extensive experience",
    top_skills: ["Brand strategy", "Executive leadership", "Market intuition", "Risk-taking"],
    trait_profile: { quadrant_a: 0.25, quadrant_b: 0.15, quadrant_c: 0.5, quadrant_d: 0.92, pace_preference: 0.55, risk_tolerance: 0.7 },
  },
  {
    title: "Emerging Technology / Innovation Analyst",
    description: "Scouts and evaluates frontier technologies for a company to bet on, with no established playbook to follow.",
    median_salary: 118000,
    growth_pct: 14,
    education_level: "Bachelor's degree",
    top_skills: ["Technology scouting", "Trend analysis", "Strategic synthesis", "Comfort with ambiguity"],
    trait_profile: { quadrant_a: 0.45, quadrant_b: 0.2, quadrant_c: 0.25, quadrant_d: 0.9, pace_preference: 0.55, risk_tolerance: 0.75 },
  },
  {
    title: "Biotech Startup Founder",
    description: "Builds a biotech company from scratch, betting years of runway on an unproven scientific thesis.",
    median_salary: 0,
    growth_pct: 0,
    education_level: "Varies, often Ph.D. + business acumen",
    top_skills: ["Scientific judgment", "Fundraising", "Resourcefulness", "Risk tolerance"],
    trait_profile: { quadrant_a: 0.48, quadrant_b: 0.12, quadrant_c: 0.3, quadrant_d: 0.93, pace_preference: 0.65, risk_tolerance: 0.95 },
  },
  {
    title: "Venture Studio Partner",
    description: "Builds and launches multiple new companies in parallel from within a venture studio, with no fixed formula for any of them.",
    median_salary: 165000,
    growth_pct: 9,
    education_level: "Bachelor's/MBA",
    top_skills: ["Idea generation", "Rapid prototyping", "Fundraising", "Pattern recognition"],
    trait_profile: { quadrant_a: 0.25, quadrant_b: 0.1, quadrant_c: 0.48, quadrant_d: 0.95, pace_preference: 0.65, risk_tolerance: 0.9 },
  },
  {
    title: "Chief Innovation Officer",
    description: "Leads a company's search for new growth — new products, markets, or business models — at the executive level.",
    median_salary: 210000,
    growth_pct: 8,
    education_level: "Bachelor's/MBA + extensive experience",
    top_skills: ["Strategic vision", "Organizational change", "Ideation leadership", "Risk assessment"],
    trait_profile: { quadrant_a: 0.25, quadrant_b: 0.2, quadrant_c: 0.5, quadrant_d: 0.9, pace_preference: 0.55, risk_tolerance: 0.75 },
  },
  {
    title: "Marketing Manager",
    description: "Develops brand and campaign strategy, balancing creative direction with data-driven decision-making.",
    median_salary: 156580,
    growth_pct: 6,
    education_level: "Bachelor's degree",
    top_skills: ["Campaign strategy", "Data analysis", "Creative direction", "Cross-team leadership"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.2, quadrant_c: 0.48, quadrant_d: 0.85, pace_preference: 0.6, risk_tolerance: 0.5 },
  },
  {
    title: "Business Development Manager",
    description: "Identifies and closes new partnerships and revenue opportunities under real market uncertainty.",
    median_salary: 112000,
    growth_pct: 8,
    education_level: "Bachelor's degree",
    top_skills: ["Relationship building", "Negotiation", "Market opportunity analysis", "Persistence"],
    trait_profile: { quadrant_a: 0.2, quadrant_b: 0.25, quadrant_c: 0.85, quadrant_d: 0.48, pace_preference: 0.6, risk_tolerance: 0.6 },
  },
  {
    title: "Operations Manager",
    description: "Keeps a company's day-to-day processes running efficiently, solving structural bottlenecks as they arise.",
    median_salary: 100930,
    growth_pct: 6,
    education_level: "Bachelor's degree",
    top_skills: ["Process optimization", "Team coordination", "Problem-solving", "Data analysis"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.85, quadrant_c: 0.45, quadrant_d: 0.15, pace_preference: 0.55, risk_tolerance: 0.3 },
  },
  {
    title: "Logistics / Supply Chain Manager",
    description: "Coordinates the structured flow of goods through a supply chain, optimizing for cost and reliability.",
    median_salary: 98100,
    growth_pct: 18,
    education_level: "Bachelor's degree",
    top_skills: ["Process optimization", "Forecasting", "Vendor coordination", "Systems thinking"],
    trait_profile: { quadrant_a: 0.48, quadrant_b: 0.88, quadrant_c: 0.3, quadrant_d: 0.12, pace_preference: 0.55, risk_tolerance: 0.3 },
  },
  {
    title: "Executive Coach",
    description: "Advises senior leaders on decision-making, communication, and organizational effectiveness through one-on-one work.",
    median_salary: 120000,
    growth_pct: 9,
    education_level: "Bachelor's/Master's degree + coaching certification",
    top_skills: ["Active listening", "Organizational psychology", "Feedback delivery", "Relationship building"],
    trait_profile: { quadrant_a: 0.2, quadrant_b: 0.25, quadrant_c: 0.93, quadrant_d: 0.4, pace_preference: 0.4, risk_tolerance: 0.35 },
  },
  {
    title: "Private Wealth Relationship Director",
    description: "Manages high-net-worth client relationships for a bank or wealth firm, blending finance expertise with deep trust-building.",
    median_salary: 165000,
    growth_pct: 10,
    education_level: "Bachelor's degree",
    top_skills: ["Relationship management", "Financial advising", "Trust-building", "Discretion"],
    trait_profile: { quadrant_a: 0.48, quadrant_b: 0.3, quadrant_c: 0.9, quadrant_d: 0.2, pace_preference: 0.4, risk_tolerance: 0.35 },
  },
  {
    title: "Executive Recruiter",
    description: "Identifies and persuades senior leadership candidates to join client companies, working entirely through relationships.",
    median_salary: 115000,
    growth_pct: 8,
    education_level: "Bachelor's degree",
    top_skills: ["Relationship building", "Persuasion", "Networking", "Judgment of fit"],
    trait_profile: { quadrant_a: 0.15, quadrant_b: 0.25, quadrant_c: 0.92, quadrant_d: 0.45, pace_preference: 0.55, risk_tolerance: 0.5 },
  },
  {
    title: "Chief of Staff",
    description: "Operates as an executive's right hand, translating leadership priorities into action across the whole organization.",
    median_salary: 152000,
    growth_pct: 9,
    education_level: "Bachelor's/MBA",
    top_skills: ["Cross-functional coordination", "Executive communication", "Prioritization", "Discretion"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.5, quadrant_c: 0.85, quadrant_d: 0.25, pace_preference: 0.65, risk_tolerance: 0.4 },
  },

  // ---------------------------------------------------------------------
  // ENTREPRENEURSHIP / VENTURE
  // ---------------------------------------------------------------------
  {
    title: "Startup Founder / Entrepreneur",
    description: "Builds a company from scratch under deep uncertainty, allocating scarce resources with no playbook to follow.",
    median_salary: 0,
    growth_pct: 0,
    education_level: "Varies widely, no formal requirement",
    top_skills: ["Resourcefulness", "Risk tolerance", "Big-picture synthesis", "Resilience"],
    trait_profile: { quadrant_a: 0.2, quadrant_b: 0.08, quadrant_c: 0.5, quadrant_d: 0.97, pace_preference: 0.7, risk_tolerance: 0.95 },
  },
  {
    title: "Venture Capitalist",
    description: "Evaluates early-stage companies for investment under high uncertainty, betting on ambiguous, unproven ideas.",
    median_salary: 150000,
    growth_pct: 8,
    education_level: "Bachelor's/MBA",
    top_skills: ["Pattern recognition", "Risk assessment", "Networking", "Big-picture thinking"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.12, quadrant_c: 0.5, quadrant_d: 0.88, pace_preference: 0.55, risk_tolerance: 0.85 },
  },

  // ---------------------------------------------------------------------
  // SCIENCE / RESEARCH / ACADEMIA
  // ---------------------------------------------------------------------
  {
    title: "Physicist",
    description: "Conducts research into the fundamental laws governing matter and energy, often via experiment and modeling.",
    median_salary: 155680,
    growth_pct: 7,
    education_level: "Ph.D.",
    top_skills: ["Mathematical modeling", "Experimental design", "Analytical reasoning", "Research"],
    trait_profile: { quadrant_a: 0.97, quadrant_b: 0.25, quadrant_c: 0.08, quadrant_d: 0.42, pace_preference: 0.2, risk_tolerance: 0.25 },
  },
  {
    title: "Astrophysicist",
    description: "Studies celestial bodies and the physics of the universe through observation, theory, and computation.",
    median_salary: 148000,
    growth_pct: 8,
    education_level: "Ph.D.",
    top_skills: ["Mathematical modeling", "Data analysis", "Research methodology", "Programming"],
    trait_profile: { quadrant_a: 0.96, quadrant_b: 0.25, quadrant_c: 0.08, quadrant_d: 0.45, pace_preference: 0.2, risk_tolerance: 0.3 },
  },
  {
    title: "University Professor",
    description: "Conducts original research and teaches at the postsecondary level, balancing structured teaching with open-ended inquiry.",
    median_salary: 84380,
    growth_pct: 6,
    education_level: "Ph.D.",
    top_skills: ["Research design", "Subject expertise", "Teaching", "Academic writing"],
    trait_profile: { quadrant_a: 0.85, quadrant_b: 0.2, quadrant_c: 0.5, quadrant_d: 0.3, pace_preference: 0.25, risk_tolerance: 0.3 },
  },
  {
    title: "Environmental Scientist",
    description: "Studies environmental conditions and impacts, often designing novel field studies under ambiguity.",
    median_salary: 78980,
    growth_pct: 6,
    education_level: "Bachelor's/Master's degree",
    top_skills: ["Field research", "Data analysis", "Report writing", "Regulatory knowledge"],
    trait_profile: { quadrant_a: 0.85, quadrant_b: 0.3, quadrant_c: 0.2, quadrant_d: 0.45, pace_preference: 0.3, risk_tolerance: 0.3 },
  },

  // ---------------------------------------------------------------------
  // ARCHITECTURE / PLANNING
  // ---------------------------------------------------------------------
  {
    title: "Architect",
    description: "Designs buildings balancing creative vision, client constraints, and structural feasibility under real ambiguity.",
    median_salary: 93310,
    growth_pct: 4,
    education_level: "Bachelor's/Master's degree + licensure",
    top_skills: ["Spatial design", "Creative problem-solving", "Client communication", "Technical drafting"],
    trait_profile: { quadrant_a: 0.45, quadrant_b: 0.25, quadrant_c: 0.3, quadrant_d: 0.85, pace_preference: 0.35, risk_tolerance: 0.45 },
  },
  {
    title: "Urban Planner",
    description: "Designs land-use and development plans for communities, balancing regulation with creative long-term vision.",
    median_salary: 82160,
    growth_pct: 4,
    education_level: "Master's degree",
    top_skills: ["Zoning/regulatory knowledge", "Long-term visioning", "Stakeholder communication", "Data analysis"],
    trait_profile: { quadrant_a: 0.25, quadrant_b: 0.85, quadrant_c: 0.3, quadrant_d: 0.48, pace_preference: 0.3, risk_tolerance: 0.35 },
  },

  // ---------------------------------------------------------------------
  // GOVERNMENT / INTERNATIONAL AFFAIRS
  // ---------------------------------------------------------------------
  {
    title: "Diplomat / Foreign Service Officer",
    description: "Represents national interests abroad, negotiates between parties, and manages sensitive interpersonal relationships.",
    median_salary: 108000,
    growth_pct: 3,
    education_level: "Bachelor's/Master's degree + Foreign Service exam",
    top_skills: ["Negotiation", "Cross-cultural communication", "Conflict mediation", "Political judgment"],
    trait_profile: { quadrant_a: 0.15, quadrant_b: 0.3, quadrant_c: 0.9, quadrant_d: 0.45, pace_preference: 0.4, risk_tolerance: 0.4 },
  },
];

// ---------------------------------------------------------------------
// ALTERNATIVE PATHS — deliberately small, secondary coverage.
// For users who genuinely want a hands-on, vocational, or non-corporate
// path. Present, but not competing for depth with the set above.
// ---------------------------------------------------------------------
export const alternativePaths = [
  {
    title: "Airline Pilot",
    description: "Operates aircraft following strict procedural checklists and regulatory protocol; high responsibility, low error tolerance.",
    median_salary: 219140,
    growth_pct: 5,
    education_level: "Bachelor's degree + flight certification",
    top_skills: ["Procedural discipline", "Situational awareness", "Checklist execution", "Composure under pressure"],
    trait_profile: { quadrant_a: 0.4, quadrant_b: 0.97, quadrant_c: 0.2, quadrant_d: 0.08, pace_preference: 0.6, risk_tolerance: 0.15 },
  },
  {
    title: "Veterinarian",
    description: "Diagnoses and treats animals, balancing clinical protocol with client (owner) communication.",
    median_salary: 125510,
    growth_pct: 19,
    education_level: "Doctorate (DVM)",
    top_skills: ["Clinical diagnosis", "Procedural skill", "Client communication", "Composure under pressure"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.85, quadrant_c: 0.48, quadrant_d: 0.12, pace_preference: 0.6, risk_tolerance: 0.25 },
  },
  {
    title: "Electrician",
    description: "Installs and repairs electrical systems following strict safety code and structured diagnostic procedure.",
    median_salary: 63310,
    growth_pct: 11,
    education_level: "Apprenticeship + license",
    top_skills: ["Code compliance", "Diagnostic troubleshooting", "Manual skill", "Safety protocol"],
    trait_profile: { quadrant_a: 0.45, quadrant_b: 0.88, quadrant_c: 0.2, quadrant_d: 0.12, pace_preference: 0.5, risk_tolerance: 0.2 },
  },
  {
    title: "Plumber",
    description: "Diagnoses and repairs plumbing systems following code and structured troubleshooting steps.",
    median_salary: 62970,
    growth_pct: 6,
    education_level: "Apprenticeship + license",
    top_skills: ["Diagnostic troubleshooting", "Code compliance", "Manual skill", "Customer communication"],
    trait_profile: { quadrant_a: 0.42, quadrant_b: 0.85, quadrant_c: 0.28, quadrant_d: 0.12, pace_preference: 0.5, risk_tolerance: 0.2 },
  },
  {
    title: "Firefighter",
    description: "Responds to emergencies following strict operational protocol, with sequencing decisions made in seconds.",
    median_salary: 57120,
    growth_pct: 4,
    education_level: "High school + fire academy",
    top_skills: ["Protocol adherence", "Physical readiness", "Rapid decision-making", "Teamwork under pressure"],
    trait_profile: { quadrant_a: 0.2, quadrant_b: 0.92, quadrant_c: 0.45, quadrant_d: 0.15, pace_preference: 0.9, risk_tolerance: 0.5 },
  },
  {
    title: "Police Officer",
    description: "Enforces law and responds to incidents following departmental protocol and legal procedure.",
    median_salary: 74910,
    growth_pct: 3,
    education_level: "High school/Associate degree + academy",
    top_skills: ["Protocol adherence", "Situational judgment", "Conflict de-escalation", "Report writing"],
    trait_profile: { quadrant_a: 0.2, quadrant_b: 0.88, quadrant_c: 0.48, quadrant_d: 0.12, pace_preference: 0.75, risk_tolerance: 0.45 },
  },
  {
    title: "Chef / Executive Chef",
    description: "Runs kitchen operations under nightly time pressure, balancing structured prep with creative menu development.",
    median_salary: 58920,
    growth_pct: 6,
    education_level: "Varies, often culinary school",
    top_skills: ["Kitchen management", "Creative menu design", "Speed under pressure", "Team leadership"],
    trait_profile: { quadrant_a: 0.15, quadrant_b: 0.85, quadrant_c: 0.3, quadrant_d: 0.48, pace_preference: 0.85, risk_tolerance: 0.45 },
  },
  {
    title: "Barista / Cafe Manager",
    description: "Runs day-to-day cafe operations, balancing consistent product quality with fast-paced customer service.",
    median_salary: 38000,
    growth_pct: 5,
    education_level: "High school",
    top_skills: ["Customer service", "Speed under pressure", "Multitasking", "Product consistency"],
    trait_profile: { quadrant_a: 0.15, quadrant_b: 0.48, quadrant_c: 0.85, quadrant_d: 0.3, pace_preference: 0.8, risk_tolerance: 0.3 },
  },
  {
    title: "Commercial Pilot (Charter/Cargo)",
    description: "Operates aircraft on variable routes following the same rigorous procedural checklists as commercial aviation.",
    median_salary: 106000,
    growth_pct: 5,
    education_level: "Flight certification",
    top_skills: ["Procedural discipline", "Situational awareness", "Navigation", "Composure under pressure"],
    trait_profile: { quadrant_a: 0.42, quadrant_b: 0.92, quadrant_c: 0.22, quadrant_d: 0.15, pace_preference: 0.6, risk_tolerance: 0.3 },
  },
  {
    title: "Real Estate Agent",
    description: "Guides clients through property transactions, negotiating deals and managing relationships under variable pace.",
    median_salary: 54300,
    growth_pct: 3,
    education_level: "High school + real estate license",
    top_skills: ["Negotiation", "Relationship building", "Local market knowledge", "Persistence"],
    trait_profile: { quadrant_a: 0.2, quadrant_b: 0.25, quadrant_c: 0.85, quadrant_d: 0.45, pace_preference: 0.55, risk_tolerance: 0.6 },
  },
  {
    title: "Dental Hygienist",
    description: "Provides preventive dental care following clinical protocol in a structured, appointment-based setting.",
    median_salary: 87530,
    growth_pct: 9,
    education_level: "Associate degree + license",
    top_skills: ["Clinical protocol", "Patient care", "Attention to detail", "Manual dexterity"],
    trait_profile: { quadrant_a: 0.25, quadrant_b: 0.88, quadrant_c: 0.45, quadrant_d: 0.05, pace_preference: 0.45, risk_tolerance: 0.1 },
  },
  {
    title: "Graphic Designer",
    description: "Creates visual concepts and layouts for brands and media, often working within client constraints.",
    median_salary: 60510,
    growth_pct: 3,
    education_level: "Bachelor's degree",
    top_skills: ["Visual design", "Software tools (Adobe suite)", "Creative concepting", "Client feedback iteration"],
    trait_profile: { quadrant_a: 0.2, quadrant_b: 0.25, quadrant_c: 0.42, quadrant_d: 0.88, pace_preference: 0.45, risk_tolerance: 0.4 },
  },
  {
    title: "Elementary School Teacher",
    description: "Plans and delivers structured lessons daily, balancing curriculum requirements with individual student needs.",
    median_salary: 63670,
    growth_pct: 1,
    education_level: "Bachelor's degree + certification",
    top_skills: ["Lesson planning", "Classroom management", "Patience", "Communication"],
    trait_profile: { quadrant_a: 0.2, quadrant_b: 0.5, quadrant_c: 0.88, quadrant_d: 0.25, pace_preference: 0.4, risk_tolerance: 0.2 },
  },
  {
    title: "Event Planner",
    description: "Coordinates complex logistics for events, blending tight sequencing with creative problem-solving on the fly.",
    median_salary: 56770,
    growth_pct: 7,
    education_level: "Bachelor's degree",
    top_skills: ["Vendor coordination", "Sequencing under pressure", "Creative troubleshooting", "Client communication"],
    trait_profile: { quadrant_a: 0.15, quadrant_b: 0.85, quadrant_c: 0.28, quadrant_d: 0.45, pace_preference: 0.75, risk_tolerance: 0.4 },
  },
  {
    title: "Film / TV Director",
    description: "Shapes creative vision for a production, making high-stakes artistic calls with no single right answer.",
    median_salary: 85320,
    growth_pct: 7,
    education_level: "Varies, often no formal requirement",
    top_skills: ["Creative vision", "Improvisation", "Risk-taking", "Collaborative leadership"],
    trait_profile: { quadrant_a: 0.1, quadrant_b: 0.15, quadrant_c: 0.5, quadrant_d: 0.95, pace_preference: 0.5, risk_tolerance: 0.75 },
  },
];
