// Draft occupation dataset — one-time LLM-assisted trait-profile pass.
// trait_profile dimensions (0-1 each):
//   quadrant_a: analytical/quantitative (Financial Analyst archetype)
//   quadrant_b: sequential/structured (ER Physician archetype)
//   quadrant_c: relational/interpersonal (Executive/People Leader archetype)
//   quadrant_d: experimental/big-picture (Startup Founder archetype)
//   pace_preference: 0 = slow/deliberate, 1 = fast/urgent
//   risk_tolerance: 0 = risk-averse, 1 = risk-seeking
//
// Salary/growth figures are approximate, drawn from general knowledge of
// recent BLS Occupational Outlook Handbook ranges — NOT a live pull.
// Flagged for manual review before hard-coding per the build plan's
// one-time-LLM-pass-then-human-review process. Spot-check before launch.

export const DATA_AS_OF = "2025-09-01";

export const occupations = [
  {
    title: "Investment Analyst",
    description: "Evaluates securities, builds financial models, and makes buy/sell/hold recommendations for portfolios or clients.",
    median_salary: 99890,
    growth_pct: 8,
    education_level: "Bachelor's degree",
    top_skills: ["Financial modeling", "Quantitative analysis", "Valuation", "Excel/SQL"],
    trait_profile: { quadrant_a: 0.95, quadrant_b: 0.55, quadrant_c: 0.25, quadrant_d: 0.35, pace_preference: 0.6, risk_tolerance: 0.55 },
  },
  {
    title: "Actuary",
    description: "Uses statistics and financial theory to assess risk for insurance, pensions, and investment decisions.",
    median_salary: 120000,
    growth_pct: 22,
    education_level: "Bachelor's degree + actuarial exams",
    top_skills: ["Statistics", "Risk modeling", "Probability", "Programming"],
    trait_profile: { quadrant_a: 0.97, quadrant_b: 0.7, quadrant_c: 0.15, quadrant_d: 0.15, pace_preference: 0.3, risk_tolerance: 0.15 },
  },
  {
    title: "Data Scientist",
    description: "Builds statistical models and machine learning systems to extract insight and drive product/business decisions.",
    median_salary: 108020,
    growth_pct: 36,
    education_level: "Bachelor's/Master's degree",
    top_skills: ["Statistics", "Python/R", "Machine learning", "Data visualization"],
    trait_profile: { quadrant_a: 0.9, quadrant_b: 0.45, quadrant_c: 0.2, quadrant_d: 0.55, pace_preference: 0.5, risk_tolerance: 0.4 },
  },
  {
    title: "Accountant / Auditor",
    description: "Prepares and examines financial records, ensures accuracy and regulatory compliance.",
    median_salary: 79880,
    growth_pct: 4,
    education_level: "Bachelor's degree",
    top_skills: ["GAAP", "Attention to detail", "Excel", "Regulatory compliance"],
    trait_profile: { quadrant_a: 0.8, quadrant_b: 0.85, quadrant_c: 0.2, quadrant_d: 0.05, pace_preference: 0.35, risk_tolerance: 0.1 },
  },
  {
    title: "Economist",
    description: "Studies production and distribution of resources, forecasts trends, and advises on policy or business strategy.",
    median_salary: 115730,
    growth_pct: 5,
    education_level: "Master's degree",
    top_skills: ["Econometrics", "Statistical modeling", "Research", "Writing"],
    trait_profile: { quadrant_a: 0.9, quadrant_b: 0.5, quadrant_c: 0.25, quadrant_d: 0.35, pace_preference: 0.3, risk_tolerance: 0.2 },
  },
  {
    title: "Emergency Medicine Physician",
    description: "Diagnoses and treats acute illness and injury under time pressure in a hospital emergency department.",
    median_salary: 310640,
    growth_pct: 4,
    education_level: "M.D./D.O. + residency",
    top_skills: ["Triage", "Clinical protocol", "Rapid decision-making", "Procedural skill"],
    trait_profile: { quadrant_a: 0.5, quadrant_b: 0.95, quadrant_c: 0.55, quadrant_d: 0.2, pace_preference: 0.95, risk_tolerance: 0.4 },
  },
  {
    title: "Registered Nurse",
    description: "Provides direct patient care, administers treatment, and coordinates with physicians under clinical protocol.",
    median_salary: 86070,
    growth_pct: 6,
    education_level: "Bachelor's/Associate degree + license",
    top_skills: ["Clinical care", "Protocol adherence", "Patient communication", "Multitasking"],
    trait_profile: { quadrant_a: 0.35, quadrant_b: 0.85, quadrant_c: 0.65, quadrant_d: 0.1, pace_preference: 0.75, risk_tolerance: 0.2 },
  },
  {
    title: "Airline Pilot",
    description: "Operates aircraft following strict procedural checklists and regulatory protocol; high responsibility, low error tolerance.",
    median_salary: 219140,
    growth_pct: 5,
    education_level: "Bachelor's degree + flight certification",
    top_skills: ["Procedural discipline", "Situational awareness", "Checklist execution", "Composure under pressure"],
    trait_profile: { quadrant_a: 0.5, quadrant_b: 0.97, quadrant_c: 0.3, quadrant_d: 0.1, pace_preference: 0.6, risk_tolerance: 0.15 },
  },
  {
    title: "Air Traffic Controller",
    description: "Directs aircraft movement to maintain safe separation, following rigid sequencing protocol under constant time pressure.",
    median_salary: 137380,
    growth_pct: 3,
    education_level: "Associate degree + FAA certification",
    top_skills: ["Sequencing", "Protocol adherence", "Focus under pressure", "Spatial reasoning"],
    trait_profile: { quadrant_a: 0.55, quadrant_b: 0.95, quadrant_c: 0.2, quadrant_d: 0.05, pace_preference: 0.9, risk_tolerance: 0.1 },
  },
  {
    title: "Pharmacist",
    description: "Dispenses medication, verifies dosage safety, and advises patients following strict regulatory protocol.",
    median_salary: 136030,
    growth_pct: 3,
    education_level: "Pharm.D. degree",
    top_skills: ["Pharmacology", "Protocol verification", "Attention to detail", "Patient counseling"],
    trait_profile: { quadrant_a: 0.65, quadrant_b: 0.9, quadrant_c: 0.4, quadrant_d: 0.05, pace_preference: 0.5, risk_tolerance: 0.1 },
  },
  {
    title: "Civil Engineer",
    description: "Designs and oversees infrastructure projects following building codes, safety standards, and structured project phases.",
    median_salary: 95890,
    growth_pct: 5,
    education_level: "Bachelor's degree + P.E. license",
    top_skills: ["Structural analysis", "CAD", "Code compliance", "Project sequencing"],
    trait_profile: { quadrant_a: 0.75, quadrant_b: 0.8, quadrant_c: 0.3, quadrant_d: 0.2, pace_preference: 0.35, risk_tolerance: 0.15 },
  },
  {
    title: "Air Force / Military Officer",
    description: "Executes mission-critical operations under strict chain-of-command protocol and standardized procedure.",
    median_salary: 98000,
    growth_pct: 2,
    education_level: "Bachelor's degree + officer training",
    top_skills: ["Protocol adherence", "Leadership under structure", "Discipline", "Tactical planning"],
    trait_profile: { quadrant_a: 0.4, quadrant_b: 0.9, quadrant_c: 0.5, quadrant_d: 0.15, pace_preference: 0.7, risk_tolerance: 0.35 },
  },
  {
    title: "Paralegal",
    description: "Prepares legal documents, organizes case files, and ensures procedural compliance for attorneys.",
    median_salary: 60970,
    growth_pct: 1,
    education_level: "Associate/Bachelor's degree",
    top_skills: ["Legal research", "Document organization", "Procedural accuracy", "Writing"],
    trait_profile: { quadrant_a: 0.55, quadrant_b: 0.85, quadrant_c: 0.3, quadrant_d: 0.05, pace_preference: 0.4, risk_tolerance: 0.1 },
  },
  {
    title: "Chief Executive Officer",
    description: "Sets organizational strategy and culture, resolves cross-functional conflict, and represents the company to stakeholders.",
    median_salary: 206680,
    growth_pct: 6,
    education_level: "Bachelor's/MBA (varies widely)",
    top_skills: ["Strategic vision", "People leadership", "Conflict mediation", "Communication"],
    trait_profile: { quadrant_a: 0.4, quadrant_b: 0.3, quadrant_c: 0.85, quadrant_d: 0.65, pace_preference: 0.6, risk_tolerance: 0.6 },
  },
  {
    title: "Human Resources Manager",
    description: "Manages hiring, employee relations, and workplace conflict resolution across an organization.",
    median_salary: 136350,
    growth_pct: 6,
    education_level: "Bachelor's degree",
    top_skills: ["Conflict resolution", "Empathetic listening", "Policy design", "Negotiation"],
    trait_profile: { quadrant_a: 0.25, quadrant_b: 0.45, quadrant_c: 0.9, quadrant_d: 0.25, pace_preference: 0.45, risk_tolerance: 0.25 },
  },
  {
    title: "School Counselor",
    description: "Supports students' academic, social, and emotional development through one-on-one and group guidance.",
    median_salary: 61710,
    growth_pct: 5,
    education_level: "Master's degree",
    top_skills: ["Active listening", "Empathy", "Conflict mediation", "Adolescent development"],
    trait_profile: { quadrant_a: 0.15, quadrant_b: 0.35, quadrant_c: 0.95, quadrant_d: 0.15, pace_preference: 0.3, risk_tolerance: 0.15 },
  },
  {
    title: "Social Worker",
    description: "Helps individuals and families cope with challenges, coordinating access to social services and support.",
    median_salary: 58380,
    growth_pct: 7,
    education_level: "Bachelor's/Master's degree",
    top_skills: ["Empathy", "Crisis intervention", "Case management", "Active listening"],
    trait_profile: { quadrant_a: 0.15, quadrant_b: 0.4, quadrant_c: 0.95, quadrant_d: 0.2, pace_preference: 0.45, risk_tolerance: 0.2 },
  },
  {
    title: "Sales Manager",
    description: "Leads a sales team, resolves client and internal team conflict, and drives revenue through relationship-building.",
    median_salary: 135160,
    growth_pct: 4,
    education_level: "Bachelor's degree",
    top_skills: ["Relationship building", "Negotiation", "Team leadership", "Persuasion"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.35, quadrant_c: 0.8, quadrant_d: 0.45, pace_preference: 0.65, risk_tolerance: 0.5 },
  },
  {
    title: "Marriage and Family Therapist",
    description: "Provides talk therapy to individuals, couples, and families to resolve relational and emotional conflict.",
    median_salary: 63780,
    growth_pct: 15,
    education_level: "Master's degree + license",
    top_skills: ["Active listening", "Empathy", "Conflict mediation", "Clinical judgment"],
    trait_profile: { quadrant_a: 0.2, quadrant_b: 0.4, quadrant_c: 0.97, quadrant_d: 0.15, pace_preference: 0.3, risk_tolerance: 0.15 },
  },
  {
    title: "Diplomat / Foreign Service Officer",
    description: "Represents national interests abroad, negotiates between parties, and manages sensitive interpersonal relationships.",
    median_salary: 108000,
    growth_pct: 3,
    education_level: "Bachelor's/Master's degree + Foreign Service exam",
    top_skills: ["Negotiation", "Cross-cultural communication", "Conflict mediation", "Political judgment"],
    trait_profile: { quadrant_a: 0.35, quadrant_b: 0.45, quadrant_c: 0.85, quadrant_d: 0.45, pace_preference: 0.4, risk_tolerance: 0.4 },
  },
  {
    title: "Hotel General Manager",
    description: "Oversees property operations, staff, and guest relations, mediating disputes between staff and guests daily.",
    median_salary: 65200,
    growth_pct: 6,
    education_level: "Bachelor's degree (hospitality)",
    top_skills: ["Team leadership", "Customer relations", "Conflict resolution", "Operations"],
    trait_profile: { quadrant_a: 0.2, quadrant_b: 0.5, quadrant_c: 0.85, quadrant_d: 0.3, pace_preference: 0.55, risk_tolerance: 0.3 },
  },
  {
    title: "Startup Founder / Entrepreneur",
    description: "Builds a company from scratch under deep uncertainty, allocating scarce resources with no playbook to follow.",
    median_salary: 0,
    growth_pct: 0,
    education_level: "Varies widely, no formal requirement",
    top_skills: ["Resourcefulness", "Risk tolerance", "Big-picture synthesis", "Resilience"],
    trait_profile: { quadrant_a: 0.35, quadrant_b: 0.1, quadrant_c: 0.5, quadrant_d: 0.97, pace_preference: 0.7, risk_tolerance: 0.95 },
  },
  {
    title: "Venture Capitalist",
    description: "Evaluates early-stage companies for investment under high uncertainty, betting on ambiguous, unproven ideas.",
    median_salary: 150000,
    growth_pct: 8,
    education_level: "Bachelor's/MBA",
    top_skills: ["Pattern recognition", "Risk assessment", "Networking", "Big-picture thinking"],
    trait_profile: { quadrant_a: 0.55, quadrant_b: 0.15, quadrant_c: 0.55, quadrant_d: 0.85, pace_preference: 0.55, risk_tolerance: 0.85 },
  },
  {
    title: "Product Manager (Tech)",
    description: "Defines product strategy and roadmap under ambiguity, synthesizing user, business, and technical constraints.",
    median_salary: 133000,
    growth_pct: 10,
    education_level: "Bachelor's degree",
    top_skills: ["Prioritization under ambiguity", "Cross-functional communication", "Strategic synthesis", "User empathy"],
    trait_profile: { quadrant_a: 0.5, quadrant_b: 0.3, quadrant_c: 0.6, quadrant_d: 0.75, pace_preference: 0.6, risk_tolerance: 0.6 },
  },
  {
    title: "Film / TV Director",
    description: "Shapes creative vision for a production, making high-stakes artistic calls with no single right answer.",
    median_salary: 85320,
    growth_pct: 7,
    education_level: "Varies, often no formal requirement",
    top_skills: ["Creative vision", "Improvisation", "Risk-taking", "Collaborative leadership"],
    trait_profile: { quadrant_a: 0.15, quadrant_b: 0.2, quadrant_c: 0.55, quadrant_d: 0.95, pace_preference: 0.5, risk_tolerance: 0.75 },
  },
  {
    title: "Architect",
    description: "Designs buildings balancing creative vision, client constraints, and structural feasibility under real ambiguity.",
    median_salary: 93310,
    growth_pct: 4,
    education_level: "Bachelor's/Master's degree + licensure",
    top_skills: ["Spatial design", "Creative problem-solving", "Client communication", "Technical drafting"],
    trait_profile: { quadrant_a: 0.5, quadrant_b: 0.45, quadrant_c: 0.4, quadrant_d: 0.75, pace_preference: 0.35, risk_tolerance: 0.45 },
  },
  {
    title: "Management Consultant",
    description: "Diagnoses ambiguous business problems for clients and proposes novel strategic solutions under time pressure.",
    median_salary: 99410,
    growth_pct: 10,
    education_level: "Bachelor's/MBA",
    top_skills: ["Structured problem-solving", "Client communication", "Strategic synthesis", "Adaptability"],
    trait_profile: { quadrant_a: 0.65, quadrant_b: 0.35, quadrant_c: 0.55, quadrant_d: 0.7, pace_preference: 0.7, risk_tolerance: 0.5 },
  },
  {
    title: "UX/Product Designer",
    description: "Explores open-ended design problems to invent new interaction models and experiences for users.",
    median_salary: 92150,
    growth_pct: 8,
    education_level: "Bachelor's degree",
    top_skills: ["Creative ideation", "User research", "Prototyping", "Visual design"],
    trait_profile: { quadrant_a: 0.35, quadrant_b: 0.3, quadrant_c: 0.55, quadrant_d: 0.8, pace_preference: 0.5, risk_tolerance: 0.55 },
  },
  {
    title: "Software Engineer",
    description: "Designs, builds, and debugs software systems, balancing structured logic with creative problem-solving.",
    median_salary: 130160,
    growth_pct: 17,
    education_level: "Bachelor's degree",
    top_skills: ["Programming", "Systems thinking", "Debugging", "Algorithm design"],
    trait_profile: { quadrant_a: 0.8, quadrant_b: 0.6, quadrant_c: 0.2, quadrant_d: 0.45, pace_preference: 0.45, risk_tolerance: 0.35 },
  },
  {
    title: "Mechanical Engineer",
    description: "Designs and tests mechanical systems and products following engineering standards and iterative prototyping.",
    median_salary: 99510,
    growth_pct: 7,
    education_level: "Bachelor's degree",
    top_skills: ["CAD", "Thermodynamics", "Prototyping", "Problem-solving"],
    trait_profile: { quadrant_a: 0.8, quadrant_b: 0.65, quadrant_c: 0.2, quadrant_d: 0.35, pace_preference: 0.35, risk_tolerance: 0.3 },
  },
  {
    title: "Electrical Engineer",
    description: "Designs electrical systems and components, from circuits to power infrastructure, following technical standards.",
    median_salary: 109010,
    growth_pct: 5,
    education_level: "Bachelor's degree",
    top_skills: ["Circuit design", "Signal analysis", "Technical documentation", "Testing"],
    trait_profile: { quadrant_a: 0.85, quadrant_b: 0.65, quadrant_c: 0.15, quadrant_d: 0.3, pace_preference: 0.35, risk_tolerance: 0.25 },
  },
  {
    title: "Statistician",
    description: "Designs studies and analyzes data to draw statistically valid conclusions across research or business contexts.",
    median_salary: 104100,
    growth_pct: 33,
    education_level: "Master's degree",
    top_skills: ["Statistical modeling", "Study design", "Programming (R/Python)", "Data interpretation"],
    trait_profile: { quadrant_a: 0.95, quadrant_b: 0.55, quadrant_c: 0.15, quadrant_d: 0.25, pace_preference: 0.3, risk_tolerance: 0.2 },
  },
  {
    title: "Physicist",
    description: "Conducts research into the fundamental laws governing matter and energy, often via experiment and modeling.",
    median_salary: 155680,
    growth_pct: 7,
    education_level: "Ph.D.",
    top_skills: ["Mathematical modeling", "Experimental design", "Analytical reasoning", "Research"],
    trait_profile: { quadrant_a: 0.97, quadrant_b: 0.5, quadrant_c: 0.1, quadrant_d: 0.4, pace_preference: 0.2, risk_tolerance: 0.25 },
  },
  {
    title: "Biomedical Researcher",
    description: "Conducts lab research to advance medical treatment, following rigorous experimental protocol.",
    median_salary: 100890,
    growth_pct: 10,
    education_level: "Ph.D.",
    top_skills: ["Lab protocol", "Statistical analysis", "Experimental design", "Scientific writing"],
    trait_profile: { quadrant_a: 0.9, quadrant_b: 0.6, quadrant_c: 0.2, quadrant_d: 0.35, pace_preference: 0.25, risk_tolerance: 0.25 },
  },
  {
    title: "Financial Auditor (Public Accounting)",
    description: "Examines company financial statements for accuracy and compliance following strict audit procedures.",
    median_salary: 91380,
    growth_pct: 6,
    education_level: "Bachelor's degree + CPA",
    top_skills: ["Audit procedure", "Attention to detail", "GAAP", "Risk assessment"],
    trait_profile: { quadrant_a: 0.75, quadrant_b: 0.9, quadrant_c: 0.2, quadrant_d: 0.05, pace_preference: 0.4, risk_tolerance: 0.1 },
  },
  {
    title: "Surgeon",
    description: "Performs operative procedures following strict clinical protocol, often under significant time pressure.",
    median_salary: 297800,
    growth_pct: 4,
    education_level: "M.D. + surgical residency",
    top_skills: ["Procedural precision", "Protocol adherence", "Composure under pressure", "Manual dexterity"],
    trait_profile: { quadrant_a: 0.55, quadrant_b: 0.95, quadrant_c: 0.3, quadrant_d: 0.15, pace_preference: 0.75, risk_tolerance: 0.3 },
  },
  {
    title: "Firefighter",
    description: "Responds to emergencies following strict operational protocol, with sequencing decisions made in seconds.",
    median_salary: 57120,
    growth_pct: 4,
    education_level: "High school + fire academy",
    top_skills: ["Protocol adherence", "Physical readiness", "Rapid decision-making", "Teamwork under pressure"],
    trait_profile: { quadrant_a: 0.25, quadrant_b: 0.9, quadrant_c: 0.55, quadrant_d: 0.2, pace_preference: 0.9, risk_tolerance: 0.5 },
  },
  {
    title: "Police Officer",
    description: "Enforces law and responds to incidents following departmental protocol and legal procedure.",
    median_salary: 74910,
    growth_pct: 3,
    education_level: "High school/Associate degree + academy",
    top_skills: ["Protocol adherence", "Situational judgment", "Conflict de-escalation", "Report writing"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.85, quadrant_c: 0.55, quadrant_d: 0.15, pace_preference: 0.75, risk_tolerance: 0.45 },
  },
  {
    title: "Logistics / Supply Chain Manager",
    description: "Coordinates the structured flow of goods through a supply chain, optimizing for cost and reliability.",
    median_salary: 98100,
    growth_pct: 18,
    education_level: "Bachelor's degree",
    top_skills: ["Process optimization", "Forecasting", "Vendor coordination", "Systems thinking"],
    trait_profile: { quadrant_a: 0.65, quadrant_b: 0.8, quadrant_c: 0.4, quadrant_d: 0.2, pace_preference: 0.55, risk_tolerance: 0.3 },
  },
  {
    title: "Project Manager (Construction)",
    description: "Sequences and tracks construction phases against a fixed plan, coordinating trades and timelines.",
    median_salary: 104900,
    growth_pct: 8,
    education_level: "Bachelor's degree",
    top_skills: ["Scheduling", "Budget tracking", "Team coordination", "Risk management"],
    trait_profile: { quadrant_a: 0.55, quadrant_b: 0.85, quadrant_c: 0.45, quadrant_d: 0.15, pace_preference: 0.55, risk_tolerance: 0.25 },
  },
  {
    title: "Dental Hygienist",
    description: "Provides preventive dental care following clinical protocol in a structured, appointment-based setting.",
    median_salary: 87530,
    growth_pct: 9,
    education_level: "Associate degree + license",
    top_skills: ["Clinical protocol", "Patient care", "Attention to detail", "Manual dexterity"],
    trait_profile: { quadrant_a: 0.4, quadrant_b: 0.85, quadrant_c: 0.5, quadrant_d: 0.05, pace_preference: 0.45, risk_tolerance: 0.1 },
  },
  {
    title: "Elementary School Teacher",
    description: "Plans and delivers structured lessons daily, balancing curriculum requirements with individual student needs.",
    median_salary: 63670,
    growth_pct: 1,
    education_level: "Bachelor's degree + certification",
    top_skills: ["Lesson planning", "Classroom management", "Patience", "Communication"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.65, quadrant_c: 0.8, quadrant_d: 0.3, pace_preference: 0.4, risk_tolerance: 0.2 },
  },
  {
    title: "University Professor",
    description: "Conducts original research and teaches at the postsecondary level, balancing structured teaching with open-ended inquiry.",
    median_salary: 84380,
    growth_pct: 6,
    education_level: "Ph.D.",
    top_skills: ["Research design", "Subject expertise", "Teaching", "Academic writing"],
    trait_profile: { quadrant_a: 0.7, quadrant_b: 0.45, quadrant_c: 0.45, quadrant_d: 0.55, pace_preference: 0.25, risk_tolerance: 0.3 },
  },
  {
    title: "Journalist",
    description: "Investigates and reports stories under deadline pressure, synthesizing ambiguous information into narrative.",
    median_salary: 61870,
    growth_pct: -3,
    education_level: "Bachelor's degree",
    top_skills: ["Research", "Writing", "Interviewing", "Fast synthesis under deadline"],
    trait_profile: { quadrant_a: 0.5, quadrant_b: 0.4, quadrant_c: 0.6, quadrant_d: 0.65, pace_preference: 0.75, risk_tolerance: 0.5 },
  },
  {
    title: "Public Relations Specialist",
    description: "Manages an organization's public image, crafting messaging and handling reputational crises.",
    median_salary: 67440,
    growth_pct: 6,
    education_level: "Bachelor's degree",
    top_skills: ["Messaging strategy", "Crisis communication", "Relationship building", "Writing"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.4, quadrant_c: 0.8, quadrant_d: 0.5, pace_preference: 0.6, risk_tolerance: 0.45 },
  },
  {
    title: "Real Estate Agent",
    description: "Guides clients through property transactions, negotiating deals and managing relationships under variable pace.",
    median_salary: 54300,
    growth_pct: 3,
    education_level: "High school + real estate license",
    top_skills: ["Negotiation", "Relationship building", "Local market knowledge", "Persistence"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.35, quadrant_c: 0.75, quadrant_d: 0.5, pace_preference: 0.55, risk_tolerance: 0.6 },
  },
  {
    title: "Chef / Executive Chef",
    description: "Runs kitchen operations under nightly time pressure, balancing structured prep with creative menu development.",
    median_salary: 58920,
    growth_pct: 6,
    education_level: "Varies, often culinary school",
    top_skills: ["Kitchen management", "Creative menu design", "Speed under pressure", "Team leadership"],
    trait_profile: { quadrant_a: 0.2, quadrant_b: 0.7, quadrant_c: 0.45, quadrant_d: 0.6, pace_preference: 0.85, risk_tolerance: 0.45 },
  },
  {
    title: "Graphic Designer",
    description: "Creates visual concepts and layouts for brands and media, often working within client constraints.",
    median_salary: 60510,
    growth_pct: 3,
    education_level: "Bachelor's degree",
    top_skills: ["Visual design", "Software tools (Adobe suite)", "Creative concepting", "Client feedback iteration"],
    trait_profile: { quadrant_a: 0.25, quadrant_b: 0.4, quadrant_c: 0.4, quadrant_d: 0.8, pace_preference: 0.45, risk_tolerance: 0.4 },
  },
  {
    title: "Marketing Manager",
    description: "Develops brand and campaign strategy, balancing creative direction with data-driven decision-making.",
    median_salary: 156580,
    growth_pct: 6,
    education_level: "Bachelor's degree",
    top_skills: ["Campaign strategy", "Data analysis", "Creative direction", "Cross-team leadership"],
    trait_profile: { quadrant_a: 0.5, quadrant_b: 0.35, quadrant_c: 0.6, quadrant_d: 0.65, pace_preference: 0.6, risk_tolerance: 0.5 },
  },
  {
    title: "Physical Therapist",
    description: "Designs and delivers rehabilitation plans following clinical protocol, adjusting to each patient's progress.",
    median_salary: 99710,
    growth_pct: 14,
    education_level: "Doctorate (DPT)",
    top_skills: ["Clinical assessment", "Treatment planning", "Patient communication", "Anatomy knowledge"],
    trait_profile: { quadrant_a: 0.45, quadrant_b: 0.75, quadrant_c: 0.65, quadrant_d: 0.15, pace_preference: 0.45, risk_tolerance: 0.2 },
  },
  {
    title: "Occupational Therapist",
    description: "Helps patients regain daily living skills through individualized, protocol-guided therapeutic plans.",
    median_salary: 96370,
    growth_pct: 11,
    education_level: "Master's/Doctorate degree",
    top_skills: ["Patient assessment", "Treatment planning", "Empathy", "Adaptive problem-solving"],
    trait_profile: { quadrant_a: 0.35, quadrant_b: 0.7, quadrant_c: 0.75, quadrant_d: 0.2, pace_preference: 0.4, risk_tolerance: 0.15 },
  },
  {
    title: "Veterinarian",
    description: "Diagnoses and treats animals, balancing clinical protocol with client (owner) communication.",
    median_salary: 125510,
    growth_pct: 19,
    education_level: "Doctorate (DVM)",
    top_skills: ["Clinical diagnosis", "Procedural skill", "Client communication", "Composure under pressure"],
    trait_profile: { quadrant_a: 0.55, quadrant_b: 0.8, quadrant_c: 0.55, quadrant_d: 0.15, pace_preference: 0.6, risk_tolerance: 0.25 },
  },
  {
    title: "Environmental Scientist",
    description: "Studies environmental conditions and impacts, often designing novel field studies under ambiguity.",
    median_salary: 78980,
    growth_pct: 6,
    education_level: "Bachelor's/Master's degree",
    top_skills: ["Field research", "Data analysis", "Report writing", "Regulatory knowledge"],
    trait_profile: { quadrant_a: 0.75, quadrant_b: 0.55, quadrant_c: 0.3, quadrant_d: 0.45, pace_preference: 0.3, risk_tolerance: 0.3 },
  },
  {
    title: "Urban Planner",
    description: "Designs land-use and development plans for communities, balancing regulation with creative long-term vision.",
    median_salary: 82160,
    growth_pct: 4,
    education_level: "Master's degree",
    top_skills: ["Zoning/regulatory knowledge", "Long-term visioning", "Stakeholder communication", "Data analysis"],
    trait_profile: { quadrant_a: 0.55, quadrant_b: 0.55, quadrant_c: 0.5, quadrant_d: 0.55, pace_preference: 0.3, risk_tolerance: 0.35 },
  },
  {
    title: "Insurance Underwriter",
    description: "Assesses risk on applications and sets policy terms following structured underwriting guidelines.",
    median_salary: 79380,
    growth_pct: -3,
    education_level: "Bachelor's degree",
    top_skills: ["Risk assessment", "Guideline application", "Attention to detail", "Analytical judgment"],
    trait_profile: { quadrant_a: 0.75, quadrant_b: 0.8, quadrant_c: 0.25, quadrant_d: 0.1, pace_preference: 0.35, risk_tolerance: 0.15 },
  },
  {
    title: "Compliance Officer",
    description: "Ensures organizational adherence to laws and regulations through structured audits and policy enforcement.",
    median_salary: 79740,
    growth_pct: 5,
    education_level: "Bachelor's degree",
    top_skills: ["Regulatory knowledge", "Audit procedure", "Policy writing", "Attention to detail"],
    trait_profile: { quadrant_a: 0.6, quadrant_b: 0.9, quadrant_c: 0.35, quadrant_d: 0.05, pace_preference: 0.35, risk_tolerance: 0.1 },
  },
  {
    title: "Air Cargo / Operations Coordinator",
    description: "Sequences shipment logistics against tight time windows, following strict operational checklists.",
    median_salary: 48090,
    growth_pct: 5,
    education_level: "High school + on-the-job training",
    top_skills: ["Sequencing", "Time management", "Protocol adherence", "Attention to detail"],
    trait_profile: { quadrant_a: 0.4, quadrant_b: 0.85, quadrant_c: 0.3, quadrant_d: 0.1, pace_preference: 0.8, risk_tolerance: 0.25 },
  },
  {
    title: "Nonprofit Program Director",
    description: "Leads mission-driven teams and manages stakeholder relationships under resource constraints and ambiguity.",
    median_salary: 72000,
    growth_pct: 7,
    education_level: "Bachelor's/Master's degree",
    top_skills: ["Stakeholder management", "Resourcefulness", "Team leadership", "Grant strategy"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.4, quadrant_c: 0.85, quadrant_d: 0.55, pace_preference: 0.5, risk_tolerance: 0.45 },
  },
  {
    title: "Talent Agent",
    description: "Negotiates deals and manages relationships for clients in an unpredictable, relationship-driven industry.",
    median_salary: 78980,
    growth_pct: 6,
    education_level: "Bachelor's degree",
    top_skills: ["Negotiation", "Relationship building", "Networking", "Deal-making under ambiguity"],
    trait_profile: { quadrant_a: 0.25, quadrant_b: 0.2, quadrant_c: 0.8, quadrant_d: 0.65, pace_preference: 0.65, risk_tolerance: 0.65 },
  },
  {
    title: "Event Planner",
    description: "Coordinates complex logistics for events, blending tight sequencing with creative problem-solving on the fly.",
    median_salary: 56770,
    growth_pct: 7,
    education_level: "Bachelor's degree",
    top_skills: ["Vendor coordination", "Sequencing under pressure", "Creative troubleshooting", "Client communication"],
    trait_profile: { quadrant_a: 0.3, quadrant_b: 0.7, quadrant_c: 0.6, quadrant_d: 0.45, pace_preference: 0.75, risk_tolerance: 0.4 },
  },
  {
    title: "Cybersecurity Analyst",
    description: "Monitors and defends systems against threats, following incident-response protocol under time pressure.",
    median_salary: 124910,
    growth_pct: 33,
    education_level: "Bachelor's degree",
    top_skills: ["Threat analysis", "Incident response protocol", "Systems thinking", "Rapid triage"],
    trait_profile: { quadrant_a: 0.85, quadrant_b: 0.8, quadrant_c: 0.15, quadrant_d: 0.3, pace_preference: 0.7, risk_tolerance: 0.3 },
  },
  {
    title: "Pastry Chef / Baker",
    description: "Executes precise, repeatable recipes at scale, balancing consistency with creative product development.",
    median_salary: 42130,
    growth_pct: 4,
    education_level: "Varies, often culinary training",
    top_skills: ["Precision", "Recipe development", "Time management", "Attention to detail"],
    trait_profile: { quadrant_a: 0.4, quadrant_b: 0.8, quadrant_c: 0.3, quadrant_d: 0.4, pace_preference: 0.55, risk_tolerance: 0.25 },
  },
  {
    title: "Electrician",
    description: "Installs and repairs electrical systems following strict safety code and structured diagnostic procedure.",
    median_salary: 63310,
    growth_pct: 11,
    education_level: "Apprenticeship + license",
    top_skills: ["Code compliance", "Diagnostic troubleshooting", "Manual skill", "Safety protocol"],
    trait_profile: { quadrant_a: 0.5, quadrant_b: 0.85, quadrant_c: 0.25, quadrant_d: 0.15, pace_preference: 0.5, risk_tolerance: 0.2 },
  },
  {
    title: "Plumber",
    description: "Diagnoses and repairs plumbing systems following code and structured troubleshooting steps.",
    median_salary: 62970,
    growth_pct: 6,
    education_level: "Apprenticeship + license",
    top_skills: ["Diagnostic troubleshooting", "Code compliance", "Manual skill", "Customer communication"],
    trait_profile: { quadrant_a: 0.4, quadrant_b: 0.8, quadrant_c: 0.35, quadrant_d: 0.15, pace_preference: 0.5, risk_tolerance: 0.2 },
  },
  {
    title: "Commercial Pilot (Charter/Cargo)",
    description: "Operates aircraft on variable routes following the same rigorous procedural checklists as commercial aviation.",
    median_salary: 106000,
    growth_pct: 5,
    education_level: "Flight certification",
    top_skills: ["Procedural discipline", "Situational awareness", "Navigation", "Composure under pressure"],
    trait_profile: { quadrant_a: 0.5, quadrant_b: 0.9, quadrant_c: 0.25, quadrant_d: 0.2, pace_preference: 0.6, risk_tolerance: 0.3 },
  },
  {
    title: "Film/TV Producer",
    description: "Manages the business and logistical side of a production while navigating creative and financial ambiguity.",
    median_salary: 97220,
    growth_pct: 7,
    education_level: "Bachelor's degree (varies)",
    top_skills: ["Budget management", "Stakeholder negotiation", "Risk-taking", "Cross-functional coordination"],
    trait_profile: { quadrant_a: 0.4, quadrant_b: 0.4, quadrant_c: 0.6, quadrant_d: 0.8, pace_preference: 0.55, risk_tolerance: 0.65 },
  },
  {
    title: "Game Designer",
    description: "Invents rules, mechanics, and player experiences from scratch, iterating through open-ended prototyping.",
    median_salary: 89410,
    growth_pct: 8,
    education_level: "Bachelor's degree",
    top_skills: ["Systems design", "Creative ideation", "Prototyping", "Playtesting iteration"],
    trait_profile: { quadrant_a: 0.45, quadrant_b: 0.35, quadrant_c: 0.35, quadrant_d: 0.85, pace_preference: 0.5, risk_tolerance: 0.55 },
  },
  {
    title: "Litigation Attorney",
    description: "Builds and argues legal cases, combining rigorous procedural preparation with adversarial persuasion.",
    median_salary: 145760,
    growth_pct: 5,
    education_level: "J.D. + bar admission",
    top_skills: ["Legal research", "Argumentation", "Procedural discipline", "Persuasive writing"],
    trait_profile: { quadrant_a: 0.7, quadrant_b: 0.75, quadrant_c: 0.55, quadrant_d: 0.3, pace_preference: 0.6, risk_tolerance: 0.4 },
  },
  {
    title: "Corporate Lawyer (Transactional)",
    description: "Structures deals and contracts, balancing precise procedural drafting with client relationship management.",
    median_salary: 145760,
    growth_pct: 5,
    education_level: "J.D. + bar admission",
    top_skills: ["Contract drafting", "Negotiation", "Regulatory knowledge", "Client management"],
    trait_profile: { quadrant_a: 0.65, quadrant_b: 0.8, quadrant_c: 0.5, quadrant_d: 0.2, pace_preference: 0.45, risk_tolerance: 0.25 },
  },
  {
    title: "Air Quality / Field Inspector",
    description: "Conducts standardized inspections against fixed regulatory checklists in the field.",
    median_salary: 67230,
    growth_pct: 4,
    education_level: "Bachelor's degree",
    top_skills: ["Checklist execution", "Regulatory knowledge", "Report writing", "Attention to detail"],
    trait_profile: { quadrant_a: 0.55, quadrant_b: 0.85, quadrant_c: 0.3, quadrant_d: 0.1, pace_preference: 0.4, risk_tolerance: 0.15 },
  },
  {
    title: "Behavioral / Clinical Psychologist",
    description: "Assesses and treats mental health conditions through structured therapeutic frameworks and deep interpersonal work.",
    median_salary: 92740,
    growth_pct: 7,
    education_level: "Doctorate (Ph.D./Psy.D.)",
    top_skills: ["Clinical assessment", "Active listening", "Treatment planning", "Empathy"],
    trait_profile: { quadrant_a: 0.45, quadrant_b: 0.5, quadrant_c: 0.9, quadrant_d: 0.25, pace_preference: 0.3, risk_tolerance: 0.15 },
  },
];
